// <auto-generated>
//     Generated by tools/resx-gen.ps1 from Strings.resx. DO NOT EDIT BY HAND:
//     run the tool, or `./build.ps1 check` will fail the resx-audit gate on the drift.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace FrameLedger.Shared;

/// <summary>The user-visible strings (docs/09_I18N.md), one property per key, read through the current UI culture.</summary>
[GeneratedCode("tools/resx-gen.ps1", "1")]
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>The culture the properties read with; null means the current UI culture.</summary>
    public static CultureInfo? Culture { get; set; }

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("FrameLedger.Shared.Strings", typeof(Strings).Assembly);

    /// <summary>Every key, for an audit that walks them.</summary>
    public static IReadOnlyList<string> Keys { get; } =
    [
        nameof(Safety_AutoDisabled_Format),
        nameof(Safety_Blocked_Toggle_Format),
        nameof(Safety_Consent_AgentUnavailable),
        nameof(Safety_Consent_AntiCheat),
        nameof(Safety_Consent_Enable),
        nameof(Safety_Consent_Hooked),
        nameof(Safety_Consent_Injected),
        nameof(Safety_Consent_Intro),
        nameof(Safety_Consent_KeepOff),
        nameof(Safety_Consent_NotHooked),
        nameof(Safety_Consent_Phrase),
        nameof(Safety_Consent_Terms),
        nameof(Safety_Consent_Title_Format),
        nameof(Safety_Consent_TypeToConfirm_Format),
        nameof(Safety_Consent_VersionMismatch),
        nameof(Safety_HookingTurnedOff),
        nameof(Safety_RecordWithoutMeasuring),
        nameof(Safety_Refused_CouldNotVerify),
        nameof(Safety_Refused_Named_Format),
        nameof(Safety_Refused_TargetUnreadable),
        nameof(Safety_Refused_Unnamed),
        nameof(Safety_Unhooked_Format),
    ];

    public static string Safety_AutoDisabled_Format => ResourceManager.GetString(nameof(Safety_AutoDisabled_Format), Culture) ?? nameof(Safety_AutoDisabled_Format);

    public static string Safety_Blocked_Toggle_Format => ResourceManager.GetString(nameof(Safety_Blocked_Toggle_Format), Culture) ?? nameof(Safety_Blocked_Toggle_Format);

    public static string Safety_Consent_AgentUnavailable => ResourceManager.GetString(nameof(Safety_Consent_AgentUnavailable), Culture) ?? nameof(Safety_Consent_AgentUnavailable);

    public static string Safety_Consent_AntiCheat => ResourceManager.GetString(nameof(Safety_Consent_AntiCheat), Culture) ?? nameof(Safety_Consent_AntiCheat);

    public static string Safety_Consent_Enable => ResourceManager.GetString(nameof(Safety_Consent_Enable), Culture) ?? nameof(Safety_Consent_Enable);

    public static string Safety_Consent_Hooked => ResourceManager.GetString(nameof(Safety_Consent_Hooked), Culture) ?? nameof(Safety_Consent_Hooked);

    public static string Safety_Consent_Injected => ResourceManager.GetString(nameof(Safety_Consent_Injected), Culture) ?? nameof(Safety_Consent_Injected);

    public static string Safety_Consent_Intro => ResourceManager.GetString(nameof(Safety_Consent_Intro), Culture) ?? nameof(Safety_Consent_Intro);

    public static string Safety_Consent_KeepOff => ResourceManager.GetString(nameof(Safety_Consent_KeepOff), Culture) ?? nameof(Safety_Consent_KeepOff);

    public static string Safety_Consent_NotHooked => ResourceManager.GetString(nameof(Safety_Consent_NotHooked), Culture) ?? nameof(Safety_Consent_NotHooked);

    public static string Safety_Consent_Phrase => ResourceManager.GetString(nameof(Safety_Consent_Phrase), Culture) ?? nameof(Safety_Consent_Phrase);

    public static string Safety_Consent_Terms => ResourceManager.GetString(nameof(Safety_Consent_Terms), Culture) ?? nameof(Safety_Consent_Terms);

    public static string Safety_Consent_Title_Format => ResourceManager.GetString(nameof(Safety_Consent_Title_Format), Culture) ?? nameof(Safety_Consent_Title_Format);

    public static string Safety_Consent_TypeToConfirm_Format => ResourceManager.GetString(nameof(Safety_Consent_TypeToConfirm_Format), Culture) ?? nameof(Safety_Consent_TypeToConfirm_Format);

    public static string Safety_Consent_VersionMismatch => ResourceManager.GetString(nameof(Safety_Consent_VersionMismatch), Culture) ?? nameof(Safety_Consent_VersionMismatch);

    public static string Safety_HookingTurnedOff => ResourceManager.GetString(nameof(Safety_HookingTurnedOff), Culture) ?? nameof(Safety_HookingTurnedOff);

    public static string Safety_RecordWithoutMeasuring => ResourceManager.GetString(nameof(Safety_RecordWithoutMeasuring), Culture) ?? nameof(Safety_RecordWithoutMeasuring);

    public static string Safety_Refused_CouldNotVerify => ResourceManager.GetString(nameof(Safety_Refused_CouldNotVerify), Culture) ?? nameof(Safety_Refused_CouldNotVerify);

    public static string Safety_Refused_Named_Format => ResourceManager.GetString(nameof(Safety_Refused_Named_Format), Culture) ?? nameof(Safety_Refused_Named_Format);

    public static string Safety_Refused_TargetUnreadable => ResourceManager.GetString(nameof(Safety_Refused_TargetUnreadable), Culture) ?? nameof(Safety_Refused_TargetUnreadable);

    public static string Safety_Refused_Unnamed => ResourceManager.GetString(nameof(Safety_Refused_Unnamed), Culture) ?? nameof(Safety_Refused_Unnamed);

    public static string Safety_Unhooked_Format => ResourceManager.GetString(nameof(Safety_Unhooked_Format), Culture) ?? nameof(Safety_Unhooked_Format);
}
