// <auto-generated>
//     Generated by tools/resx-gen.ps1 from Strings.resx. DO NOT EDIT BY HAND:
//     run the tool, or `./build.ps1 check` will fail the resx-audit gate on the drift.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace FrameLedger.App;

/// <summary>The user-visible strings (docs/09_I18N.md), one property per key, read through the current UI culture.</summary>
[GeneratedCode("tools/resx-gen.ps1", "1")]
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>The culture the properties read with; null means the current UI culture.</summary>
    public static CultureInfo? Culture { get; set; }

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("FrameLedger.App.Strings", typeof(Strings).Assembly);

    /// <summary>Every key, for an audit that walks them.</summary>
    public static IReadOnlyList<string> Keys { get; } =
    [
        nameof(About_Body_Format),
        nameof(About_Title),
        nameof(AddGame_Added_Format),
        nameof(AddGame_Dialog_Title),
        nameof(AddGame_Failed_Format),
        nameof(AddGame_Filter),
        nameof(Agent_Banner_Missing_Body),
        nameof(Agent_Banner_Offline_Body),
        nameof(Agent_Banner_Offline_Title),
        nameof(Agent_Banner_Retry),
        nameof(Agent_State_Connected),
        nameof(Agent_State_Connecting),
        nameof(Agent_State_Missing),
        nameof(Agent_State_Offline),
        nameof(Agent_State_Starting),
        nameof(App_Title),
        nameof(Chart_Axis_Count),
        nameof(Chart_Axis_Fps),
        nameof(Chart_Axis_Frametime),
        nameof(Chart_Axis_Percentile),
        nameof(Chart_Axis_Sensor),
        nameof(Chart_Axis_Time),
        nameof(Chart_Decimated_Format),
        nameof(Chart_Series_Displayed),
        nameof(Chart_Series_GpuLoad),
        nameof(Chart_Series_GpuTemp),
        nameof(Chart_Series_Native),
        nameof(Chart_Series_Percentile),
        nameof(Chart_Series_Stutter),
        nameof(Chart_Series_StutterPso),
        nameof(Chip_NA),
        nameof(Chip_No),
        nameof(Chip_Pt),
        nameof(Chip_Rr),
        nameof(Chip_Rt),
        nameof(Chip_Source_Inherited),
        nameof(Chip_Source_Manual),
        nameof(Chip_Source_Measured),
        nameof(Chip_Source_NA),
        nameof(Chip_Yes),
        nameof(Common_Cancel),
        nameof(Common_Close),
        nameof(Common_Dash),
        nameof(Common_No),
        nameof(Common_NotAvailable),
        nameof(Common_Ok),
        nameof(Common_Yes),
        nameof(Compare_Col_Date),
        nameof(Compare_Col_Fps),
        nameof(Compare_Col_Game),
        nameof(Compare_Col_MidSession),
        nameof(Compare_Col_Tier),
        nameof(Compare_Curves_Header),
        nameof(Compare_Empty),
        nameof(Compare_Export_Png),
        nameof(Compare_Header),
        nameof(Compare_Legend_Format),
        nameof(Compare_Metric_Displayed),
        nameof(Compare_Metric_Duration),
        nameof(Compare_Metric_MaxGpuTemp),
        nameof(Compare_Metric_Median),
        nameof(Compare_Metric_Native),
        nameof(Compare_Metric_P01Low),
        nameof(Compare_Metric_P1Low),
        nameof(Compare_Metric_Presented),
        nameof(Compare_Metric_StutterPct),
        nameof(Compare_Mixed_Body),
        nameof(Compare_Mixed_Legend),
        nameof(Compare_Mixed_Proceed),
        nameof(Compare_Mixed_Title),
        nameof(Compare_NoCandidates),
        nameof(Compare_Pick_Header),
        nameof(Compare_Run),
        nameof(Compare_Selected_Format),
        nameof(Compare_Table_Header),
        nameof(Compare_Table_Metric),
        nameof(Compare_TooMany),
        nameof(Crash_Body),
        nameof(Crash_Title),
        nameof(Dashboard_Agent_Elevated),
        nameof(Dashboard_Agent_Header),
        nameof(Dashboard_Agent_Overlay),
        nameof(Dashboard_Agent_Sessions),
        nameof(Dashboard_Agent_State),
        nameof(Dashboard_Agent_Telemetry),
        nameof(Dashboard_Agent_Version),
        nameof(Dashboard_Empty),
        nameof(Dashboard_Header),
        nameof(Dashboard_Live_CpuTemp_Format),
        nameof(Dashboard_Live_Elapsed_Format),
        nameof(Dashboard_Live_GpuTemp_Format),
        nameof(Dashboard_Live_Header),
        nameof(Dashboard_Live_Idle),
        nameof(Dashboard_Live_Rt_On),
        nameof(Dashboard_Live_Vram_Format),
        nameof(Dashboard_Live_Waiting),
        nameof(Dashboard_Recent_Header),
        nameof(Dashboard_SessionDiscarded_Format),
        nameof(Dashboard_SessionSaved_Format),
        nameof(Dashboard_Totals_Games),
        nameof(Dashboard_Totals_Playtime),
        nameof(Dashboard_Totals_ThisWeek),
        nameof(Diag_Written_Format),
        nameof(EditGame_Detected),
        nameof(EditGame_Name),
        nameof(EditGame_Notes),
        nameof(EditGame_Publisher),
        nameof(EditGame_Save),
        nameof(EditGame_Saved),
        nameof(EditGame_Title),
        nameof(EditGame_Version),
        nameof(Exit_Crashed),
        nameof(Exit_Degraded),
        nameof(Exit_Interrupted),
        nameof(Exit_Normal),
        nameof(Exit_UnhookedSafety),
        nameof(Fg_Active),
        nameof(Fg_None),
        nameof(Fg_Unknown),
        nameof(Format_Duration_HoursMinutes_Format),
        nameof(Format_Duration_MinutesSeconds_Format),
        nameof(Format_Playtime_Hours_Format),
        nameof(Format_Playtime_Minutes_Format),
        nameof(Format_Resolution_Format),
        nameof(Format_Resolution_Single_Format),
        nameof(Format_Temperature_Format),
        nameof(Fps_Census_NoRuntime),
        nameof(Fps_Census_NoRuntime_Tooltip),
        nameof(Fps_Census_NotRun),
        nameof(Fps_Census_NotRun_Tooltip),
        nameof(Fps_Census_RuntimeLoaded),
        nameof(Fps_Census_RuntimeLoaded_Tooltip),
        nameof(Fps_Census_Withheld),
        nameof(Fps_Census_Withheld_Tooltip),
        nameof(Fps_Fg_Chip_Format),
        nameof(Fps_Fg_Format),
        nameof(Fps_Native_Tooltip),
        nameof(Fps_None_Tooltip),
        nameof(Fps_Presented_Format),
        nameof(GameDetail_Back),
        nameof(GameDetail_Edit),
        nameof(GameDetail_Hooking_Body),
        nameof(GameDetail_Hooking_Busy),
        nameof(GameDetail_Hooking_Header),
        nameof(GameDetail_Hooking_Off),
        nameof(GameDetail_Hooking_On),
        nameof(GameDetail_Hooking_ReEnable),
        nameof(GameDetail_Hooking_Unverified),
        nameof(GameDetail_LastSession_Format),
        nameof(GameDetail_LifetimeAvg),
        nameof(GameDetail_Measured_Empty),
        nameof(GameDetail_Measured_Header),
        nameof(GameDetail_Measured_NotHooked),
        nameof(GameDetail_NotFound),
        nameof(GameDetail_Remove),
        nameof(GameDetail_Sessions_Empty),
        nameof(GameDetail_Supports_Empty),
        nameof(GameDetail_Supports_Format),
        nameof(GameDetail_Supports_Header),
        nameof(GameDetail_Tab_Distribution),
        nameof(GameDetail_Tab_Frametime),
        nameof(GameDetail_Tab_Latency),
        nameof(GameDetail_Tab_Later_Format),
        nameof(GameDetail_Tab_Sensors),
        nameof(GameDetail_Tab_Sessions),
        nameof(GameDetail_Tab_Trend),
        nameof(Games_Add),
        nameof(Games_Card_HookOff),
        nameof(Games_Card_HookOn),
        nameof(Games_Card_LastPlayed_Format),
        nameof(Games_Card_NeverPlayed),
        nameof(Games_Card_Playtime_Format),
        nameof(Games_Card_Sessions_Format),
        nameof(Games_Empty),
        nameof(Games_Header),
        nameof(Games_NoMatch),
        nameof(Games_Search_Placeholder),
        nameof(Games_Sort_Label),
        nameof(Games_Sort_LastPlayed),
        nameof(Games_Sort_Name),
        nameof(Games_Sort_Playtime),
        nameof(Latency_Avg),
        nameof(Latency_Axis),
        nameof(Latency_Empty),
        nameof(Latency_Header),
        nameof(Latency_P95),
        nameof(Latency_Series),
        nameof(Latency_Stats_Format),
        nameof(Logs_Bundle_Exported_Format),
        nameof(Logs_Bundle_Failed_Format),
        nameof(Logs_Empty),
        nameof(Logs_ExportBundle),
        nameof(Logs_Header),
        nameof(Logs_Level_All),
        nameof(Logs_Level_Error),
        nameof(Logs_Level_Warning),
        nameof(Logs_OpenFolder),
        nameof(Logs_Pause),
        nameof(Logs_Search_Placeholder),
        nameof(Logs_Showing_Format),
        nameof(Logs_Source_Agent),
        nameof(Logs_Source_Ui),
        nameof(Menu_File),
        nameof(Menu_File_AddGame),
        nameof(Menu_File_Exit),
        nameof(Menu_File_Export),
        nameof(Menu_File_ImportLibrary),
        nameof(Menu_Help),
        nameof(Menu_Help_About),
        nameof(Menu_Help_CheckUpdates),
        nameof(Menu_Help_Documentation),
        nameof(Menu_Help_ReportBug),
        nameof(Menu_Tools),
        nameof(Menu_Tools_AgentStatus),
        nameof(Menu_Tools_DbMaintenance),
        nameof(Menu_Tools_OpenDataFolder),
        nameof(Menu_Tools_UpdateRules),
        nameof(Menu_Tools_VulkanLayer),
        nameof(Nav_Compare),
        nameof(Nav_Dashboard),
        nameof(Nav_Games),
        nameof(Nav_Logs),
        nameof(Nav_Settings),
        nameof(Notice_Degraded_Body_Format),
        nameof(Notice_Degraded_Title),
        nameof(Notice_Dismiss),
        nameof(Notice_Error_Title),
        nameof(Notice_Refused_Recording),
        nameof(Notice_Refused_Title_Format),
        nameof(Notice_Unhooked_Title),
        nameof(NotYet_Body),
        nameof(NotYet_Title),
        nameof(Override_Apply),
        nameof(Override_Body),
        nameof(Override_Default),
        nameof(Override_Keep),
        nameof(Override_Title_Format),
        nameof(RemoveGame_Body),
        nameof(RemoveGame_Delete),
        nameof(RemoveGame_Keep),
        nameof(RemoveGame_Removed_Format),
        nameof(RemoveGame_Title_Format),
        nameof(Sensors_Axis_Mb),
        nameof(Sensors_Empty),
        nameof(Sensors_Series_GpuHotspot),
        nameof(Sensors_Series_GpuLoad),
        nameof(Sensors_Series_GpuPower),
        nameof(Sensors_Series_GpuTemp),
        nameof(Sensors_Series_VramAdapter),
        nameof(Sensors_Series_VramProcess),
        nameof(Sensors_Temps_Header),
        nameof(Sensors_Vram_Header),
        nameof(Sessions_Col_Api),
        nameof(Sessions_Col_Date),
        nameof(Sessions_Col_Displayed),
        nameof(Sessions_Col_Duration),
        nameof(Sessions_Col_Exit),
        nameof(Sessions_Col_Fg),
        nameof(Sessions_Col_GpuTemp),
        nameof(Sessions_Col_Native),
        nameof(Sessions_Col_P01Low),
        nameof(Sessions_Col_P1Low),
        nameof(Sessions_Col_Resolution),
        nameof(Sessions_Col_Tags),
        nameof(Sessions_Col_Tier),
        nameof(Settings_Agent_Elevated),
        nameof(Settings_Agent_Elevation_Body),
        nameof(Settings_Agent_Elevation_Label),
        nameof(Settings_Agent_Header),
        nameof(Settings_Agent_NotElevated),
        nameof(Settings_Agent_Task_Label),
        nameof(Settings_Agent_Task_Later),
        nameof(Settings_Appearance_Header),
        nameof(Settings_Applied),
        nameof(Settings_Background_Body),
        nameof(Settings_Background_Label),
        nameof(Settings_Capture_Header),
        nameof(Settings_Channel_Beta),
        nameof(Settings_Channel_Stable),
        nameof(Settings_Header),
        nameof(Settings_HookedGames_Empty),
        nameof(Settings_HookedGames_Label),
        nameof(Settings_HookedGames_Revoke),
        nameof(Settings_Interval_Body),
        nameof(Settings_Interval_Label),
        nameof(Settings_Invalid_Format),
        nameof(Settings_KillSwitch_Body),
        nameof(Settings_KillSwitch_Label),
        nameof(Settings_KillSwitch_Off),
        nameof(Settings_KillSwitch_On),
        nameof(Settings_Language_Label),
        nameof(Settings_Language_Note),
        nameof(Settings_Legal_Header),
        nameof(Settings_Legal_Reopen),
        nameof(Settings_LogDebug_Body),
        nameof(Settings_LogDebug_Label),
        nameof(Settings_Logging_Header),
        nameof(Settings_MinimizeToTray_Label),
        nameof(Settings_MinimizeToTray_Later),
        nameof(Settings_MinSession_Body),
        nameof(Settings_MinSession_Label),
        nameof(Settings_OnlineMetadata_Body),
        nameof(Settings_OnlineMetadata_Label),
        nameof(Settings_Policy_Header),
        nameof(Settings_Privacy_Header),
        nameof(Settings_Retention_Body),
        nameof(Settings_Retention_Label),
        nameof(Settings_SafetyDocs),
        nameof(Settings_StartWithWindows_Body),
        nameof(Settings_StartWithWindows_Label),
        nameof(Settings_Theme_Dark),
        nameof(Settings_Theme_Label),
        nameof(Settings_Theme_Light),
        nameof(Settings_Theme_System),
        nameof(Settings_UpdateChannel_Body),
        nameof(Settings_UpdateChannel_Label),
        nameof(Settings_Updates_Header),
        nameof(Settings_VkLayer_Label),
        nameof(Settings_VkLayer_NotRegistered),
        nameof(Settings_VkLayer_Registered),
        nameof(Settings_VkLayer_Unknown),
        nameof(Settings_Window_Header),
        nameof(Summary_Annotations_Header),
        nameof(Summary_Crash_Body),
        nameof(Summary_Crash_Title),
        nameof(Summary_Distribution_Header),
        nameof(Summary_Export_Csv),
        nameof(Summary_Export_Failed_Format),
        nameof(Summary_Export_Json),
        nameof(Summary_Export_Png),
        nameof(Summary_Export_Tier2),
        nameof(Summary_Exported_Format),
        nameof(Summary_Frametime_Header),
        nameof(Summary_Line_Format),
        nameof(Summary_Lows_Presented),
        nameof(Summary_Notes_Placeholder),
        nameof(Summary_NotFound),
        nameof(Summary_Open),
        nameof(Summary_Save),
        nameof(Summary_Saved),
        nameof(Summary_Show_Displayed),
        nameof(Summary_Show_Sensors),
        nameof(Summary_Stat_Avg),
        nameof(Summary_Stat_Duration),
        nameof(Summary_Stat_Median),
        nameof(Summary_Stat_MinMax),
        nameof(Summary_Stat_MinMax_Format),
        nameof(Summary_Stat_P01Low),
        nameof(Summary_Stat_P1Low),
        nameof(Summary_Stat_StdDev),
        nameof(Summary_Stat_StdDev_Format),
        nameof(Summary_Stat_Stutter),
        nameof(Summary_Stat_Stutter_Format),
        nameof(Summary_Tags_Placeholder),
        nameof(Summary_Tier2_Body),
        nameof(Summary_Title_Format),
        nameof(Summary_Unhooked_Body),
        nameof(Summary_Unhooked_Title),
        nameof(Tabs_SelectASession),
        nameof(Tabs_SelectedNoFrames),
        nameof(Tabs_SelectedNotHooked),
        nameof(Tier_Dash_Tooltip),
        nameof(Tier_Hooked),
        nameof(Tier_Hooked_Tooltip),
        nameof(Tier_NA_Tooltip),
        nameof(Tier_NotHooked),
        nameof(Tier_NotHooked_Tooltip),
        nameof(Trend_Average_Note),
        nameof(Trend_Axis_Date),
        nameof(Trend_Change_Cpu),
        nameof(Trend_Change_Display),
        nameof(Trend_Change_Format),
        nameof(Trend_Change_Gpu),
        nameof(Trend_Change_GpuDriver),
        nameof(Trend_Change_Os),
        nameof(Trend_Empty),
        nameof(Trend_Excluded_Format),
        nameof(Trend_IncludeMidSession),
        nameof(Trend_Metric_Average),
        nameof(Trend_Metric_Displayed),
        nameof(Trend_Metric_Label),
        nameof(Trend_Metric_MaxGpuTemp),
        nameof(Trend_Metric_P01Low),
        nameof(Trend_Metric_P1Low),
        nameof(Upscaler_None),
        nameof(Upscaler_Unknown),
    ];

    public static string About_Body_Format => ResourceManager.GetString(nameof(About_Body_Format), Culture) ?? nameof(About_Body_Format);

    public static string About_Title => ResourceManager.GetString(nameof(About_Title), Culture) ?? nameof(About_Title);

    public static string AddGame_Added_Format => ResourceManager.GetString(nameof(AddGame_Added_Format), Culture) ?? nameof(AddGame_Added_Format);

    public static string AddGame_Dialog_Title => ResourceManager.GetString(nameof(AddGame_Dialog_Title), Culture) ?? nameof(AddGame_Dialog_Title);

    public static string AddGame_Failed_Format => ResourceManager.GetString(nameof(AddGame_Failed_Format), Culture) ?? nameof(AddGame_Failed_Format);

    public static string AddGame_Filter => ResourceManager.GetString(nameof(AddGame_Filter), Culture) ?? nameof(AddGame_Filter);

    public static string Agent_Banner_Missing_Body => ResourceManager.GetString(nameof(Agent_Banner_Missing_Body), Culture) ?? nameof(Agent_Banner_Missing_Body);

    public static string Agent_Banner_Offline_Body => ResourceManager.GetString(nameof(Agent_Banner_Offline_Body), Culture) ?? nameof(Agent_Banner_Offline_Body);

    public static string Agent_Banner_Offline_Title => ResourceManager.GetString(nameof(Agent_Banner_Offline_Title), Culture) ?? nameof(Agent_Banner_Offline_Title);

    public static string Agent_Banner_Retry => ResourceManager.GetString(nameof(Agent_Banner_Retry), Culture) ?? nameof(Agent_Banner_Retry);

    public static string Agent_State_Connected => ResourceManager.GetString(nameof(Agent_State_Connected), Culture) ?? nameof(Agent_State_Connected);

    public static string Agent_State_Connecting => ResourceManager.GetString(nameof(Agent_State_Connecting), Culture) ?? nameof(Agent_State_Connecting);

    public static string Agent_State_Missing => ResourceManager.GetString(nameof(Agent_State_Missing), Culture) ?? nameof(Agent_State_Missing);

    public static string Agent_State_Offline => ResourceManager.GetString(nameof(Agent_State_Offline), Culture) ?? nameof(Agent_State_Offline);

    public static string Agent_State_Starting => ResourceManager.GetString(nameof(Agent_State_Starting), Culture) ?? nameof(Agent_State_Starting);

    public static string App_Title => ResourceManager.GetString(nameof(App_Title), Culture) ?? nameof(App_Title);

    public static string Chart_Axis_Count => ResourceManager.GetString(nameof(Chart_Axis_Count), Culture) ?? nameof(Chart_Axis_Count);

    public static string Chart_Axis_Fps => ResourceManager.GetString(nameof(Chart_Axis_Fps), Culture) ?? nameof(Chart_Axis_Fps);

    public static string Chart_Axis_Frametime => ResourceManager.GetString(nameof(Chart_Axis_Frametime), Culture) ?? nameof(Chart_Axis_Frametime);

    public static string Chart_Axis_Percentile => ResourceManager.GetString(nameof(Chart_Axis_Percentile), Culture) ?? nameof(Chart_Axis_Percentile);

    public static string Chart_Axis_Sensor => ResourceManager.GetString(nameof(Chart_Axis_Sensor), Culture) ?? nameof(Chart_Axis_Sensor);

    public static string Chart_Axis_Time => ResourceManager.GetString(nameof(Chart_Axis_Time), Culture) ?? nameof(Chart_Axis_Time);

    public static string Chart_Decimated_Format => ResourceManager.GetString(nameof(Chart_Decimated_Format), Culture) ?? nameof(Chart_Decimated_Format);

    public static string Chart_Series_Displayed => ResourceManager.GetString(nameof(Chart_Series_Displayed), Culture) ?? nameof(Chart_Series_Displayed);

    public static string Chart_Series_GpuLoad => ResourceManager.GetString(nameof(Chart_Series_GpuLoad), Culture) ?? nameof(Chart_Series_GpuLoad);

    public static string Chart_Series_GpuTemp => ResourceManager.GetString(nameof(Chart_Series_GpuTemp), Culture) ?? nameof(Chart_Series_GpuTemp);

    public static string Chart_Series_Native => ResourceManager.GetString(nameof(Chart_Series_Native), Culture) ?? nameof(Chart_Series_Native);

    public static string Chart_Series_Percentile => ResourceManager.GetString(nameof(Chart_Series_Percentile), Culture) ?? nameof(Chart_Series_Percentile);

    public static string Chart_Series_Stutter => ResourceManager.GetString(nameof(Chart_Series_Stutter), Culture) ?? nameof(Chart_Series_Stutter);

    public static string Chart_Series_StutterPso => ResourceManager.GetString(nameof(Chart_Series_StutterPso), Culture) ?? nameof(Chart_Series_StutterPso);

    public static string Chip_NA => ResourceManager.GetString(nameof(Chip_NA), Culture) ?? nameof(Chip_NA);

    public static string Chip_No => ResourceManager.GetString(nameof(Chip_No), Culture) ?? nameof(Chip_No);

    public static string Chip_Pt => ResourceManager.GetString(nameof(Chip_Pt), Culture) ?? nameof(Chip_Pt);

    public static string Chip_Rr => ResourceManager.GetString(nameof(Chip_Rr), Culture) ?? nameof(Chip_Rr);

    public static string Chip_Rt => ResourceManager.GetString(nameof(Chip_Rt), Culture) ?? nameof(Chip_Rt);

    public static string Chip_Source_Inherited => ResourceManager.GetString(nameof(Chip_Source_Inherited), Culture) ?? nameof(Chip_Source_Inherited);

    public static string Chip_Source_Manual => ResourceManager.GetString(nameof(Chip_Source_Manual), Culture) ?? nameof(Chip_Source_Manual);

    public static string Chip_Source_Measured => ResourceManager.GetString(nameof(Chip_Source_Measured), Culture) ?? nameof(Chip_Source_Measured);

    public static string Chip_Source_NA => ResourceManager.GetString(nameof(Chip_Source_NA), Culture) ?? nameof(Chip_Source_NA);

    public static string Chip_Yes => ResourceManager.GetString(nameof(Chip_Yes), Culture) ?? nameof(Chip_Yes);

    public static string Common_Cancel => ResourceManager.GetString(nameof(Common_Cancel), Culture) ?? nameof(Common_Cancel);

    public static string Common_Close => ResourceManager.GetString(nameof(Common_Close), Culture) ?? nameof(Common_Close);

    public static string Common_Dash => ResourceManager.GetString(nameof(Common_Dash), Culture) ?? nameof(Common_Dash);

    public static string Common_No => ResourceManager.GetString(nameof(Common_No), Culture) ?? nameof(Common_No);

    public static string Common_NotAvailable => ResourceManager.GetString(nameof(Common_NotAvailable), Culture) ?? nameof(Common_NotAvailable);

    public static string Common_Ok => ResourceManager.GetString(nameof(Common_Ok), Culture) ?? nameof(Common_Ok);

    public static string Common_Yes => ResourceManager.GetString(nameof(Common_Yes), Culture) ?? nameof(Common_Yes);

    public static string Compare_Col_Date => ResourceManager.GetString(nameof(Compare_Col_Date), Culture) ?? nameof(Compare_Col_Date);

    public static string Compare_Col_Fps => ResourceManager.GetString(nameof(Compare_Col_Fps), Culture) ?? nameof(Compare_Col_Fps);

    public static string Compare_Col_Game => ResourceManager.GetString(nameof(Compare_Col_Game), Culture) ?? nameof(Compare_Col_Game);

    public static string Compare_Col_MidSession => ResourceManager.GetString(nameof(Compare_Col_MidSession), Culture) ?? nameof(Compare_Col_MidSession);

    public static string Compare_Col_Tier => ResourceManager.GetString(nameof(Compare_Col_Tier), Culture) ?? nameof(Compare_Col_Tier);

    public static string Compare_Curves_Header => ResourceManager.GetString(nameof(Compare_Curves_Header), Culture) ?? nameof(Compare_Curves_Header);

    public static string Compare_Empty => ResourceManager.GetString(nameof(Compare_Empty), Culture) ?? nameof(Compare_Empty);

    public static string Compare_Export_Png => ResourceManager.GetString(nameof(Compare_Export_Png), Culture) ?? nameof(Compare_Export_Png);

    public static string Compare_Header => ResourceManager.GetString(nameof(Compare_Header), Culture) ?? nameof(Compare_Header);

    public static string Compare_Legend_Format => ResourceManager.GetString(nameof(Compare_Legend_Format), Culture) ?? nameof(Compare_Legend_Format);

    public static string Compare_Metric_Displayed => ResourceManager.GetString(nameof(Compare_Metric_Displayed), Culture) ?? nameof(Compare_Metric_Displayed);

    public static string Compare_Metric_Duration => ResourceManager.GetString(nameof(Compare_Metric_Duration), Culture) ?? nameof(Compare_Metric_Duration);

    public static string Compare_Metric_MaxGpuTemp => ResourceManager.GetString(nameof(Compare_Metric_MaxGpuTemp), Culture) ?? nameof(Compare_Metric_MaxGpuTemp);

    public static string Compare_Metric_Median => ResourceManager.GetString(nameof(Compare_Metric_Median), Culture) ?? nameof(Compare_Metric_Median);

    public static string Compare_Metric_Native => ResourceManager.GetString(nameof(Compare_Metric_Native), Culture) ?? nameof(Compare_Metric_Native);

    public static string Compare_Metric_P01Low => ResourceManager.GetString(nameof(Compare_Metric_P01Low), Culture) ?? nameof(Compare_Metric_P01Low);

    public static string Compare_Metric_P1Low => ResourceManager.GetString(nameof(Compare_Metric_P1Low), Culture) ?? nameof(Compare_Metric_P1Low);

    public static string Compare_Metric_Presented => ResourceManager.GetString(nameof(Compare_Metric_Presented), Culture) ?? nameof(Compare_Metric_Presented);

    public static string Compare_Metric_StutterPct => ResourceManager.GetString(nameof(Compare_Metric_StutterPct), Culture) ?? nameof(Compare_Metric_StutterPct);

    public static string Compare_Mixed_Body => ResourceManager.GetString(nameof(Compare_Mixed_Body), Culture) ?? nameof(Compare_Mixed_Body);

    public static string Compare_Mixed_Legend => ResourceManager.GetString(nameof(Compare_Mixed_Legend), Culture) ?? nameof(Compare_Mixed_Legend);

    public static string Compare_Mixed_Proceed => ResourceManager.GetString(nameof(Compare_Mixed_Proceed), Culture) ?? nameof(Compare_Mixed_Proceed);

    public static string Compare_Mixed_Title => ResourceManager.GetString(nameof(Compare_Mixed_Title), Culture) ?? nameof(Compare_Mixed_Title);

    public static string Compare_NoCandidates => ResourceManager.GetString(nameof(Compare_NoCandidates), Culture) ?? nameof(Compare_NoCandidates);

    public static string Compare_Pick_Header => ResourceManager.GetString(nameof(Compare_Pick_Header), Culture) ?? nameof(Compare_Pick_Header);

    public static string Compare_Run => ResourceManager.GetString(nameof(Compare_Run), Culture) ?? nameof(Compare_Run);

    public static string Compare_Selected_Format => ResourceManager.GetString(nameof(Compare_Selected_Format), Culture) ?? nameof(Compare_Selected_Format);

    public static string Compare_Table_Header => ResourceManager.GetString(nameof(Compare_Table_Header), Culture) ?? nameof(Compare_Table_Header);

    public static string Compare_Table_Metric => ResourceManager.GetString(nameof(Compare_Table_Metric), Culture) ?? nameof(Compare_Table_Metric);

    public static string Compare_TooMany => ResourceManager.GetString(nameof(Compare_TooMany), Culture) ?? nameof(Compare_TooMany);

    public static string Crash_Body => ResourceManager.GetString(nameof(Crash_Body), Culture) ?? nameof(Crash_Body);

    public static string Crash_Title => ResourceManager.GetString(nameof(Crash_Title), Culture) ?? nameof(Crash_Title);

    public static string Dashboard_Agent_Elevated => ResourceManager.GetString(nameof(Dashboard_Agent_Elevated), Culture) ?? nameof(Dashboard_Agent_Elevated);

    public static string Dashboard_Agent_Header => ResourceManager.GetString(nameof(Dashboard_Agent_Header), Culture) ?? nameof(Dashboard_Agent_Header);

    public static string Dashboard_Agent_Overlay => ResourceManager.GetString(nameof(Dashboard_Agent_Overlay), Culture) ?? nameof(Dashboard_Agent_Overlay);

    public static string Dashboard_Agent_Sessions => ResourceManager.GetString(nameof(Dashboard_Agent_Sessions), Culture) ?? nameof(Dashboard_Agent_Sessions);

    public static string Dashboard_Agent_State => ResourceManager.GetString(nameof(Dashboard_Agent_State), Culture) ?? nameof(Dashboard_Agent_State);

    public static string Dashboard_Agent_Telemetry => ResourceManager.GetString(nameof(Dashboard_Agent_Telemetry), Culture) ?? nameof(Dashboard_Agent_Telemetry);

    public static string Dashboard_Agent_Version => ResourceManager.GetString(nameof(Dashboard_Agent_Version), Culture) ?? nameof(Dashboard_Agent_Version);

    public static string Dashboard_Empty => ResourceManager.GetString(nameof(Dashboard_Empty), Culture) ?? nameof(Dashboard_Empty);

    public static string Dashboard_Header => ResourceManager.GetString(nameof(Dashboard_Header), Culture) ?? nameof(Dashboard_Header);

    public static string Dashboard_Live_CpuTemp_Format => ResourceManager.GetString(nameof(Dashboard_Live_CpuTemp_Format), Culture) ?? nameof(Dashboard_Live_CpuTemp_Format);

    public static string Dashboard_Live_Elapsed_Format => ResourceManager.GetString(nameof(Dashboard_Live_Elapsed_Format), Culture) ?? nameof(Dashboard_Live_Elapsed_Format);

    public static string Dashboard_Live_GpuTemp_Format => ResourceManager.GetString(nameof(Dashboard_Live_GpuTemp_Format), Culture) ?? nameof(Dashboard_Live_GpuTemp_Format);

    public static string Dashboard_Live_Header => ResourceManager.GetString(nameof(Dashboard_Live_Header), Culture) ?? nameof(Dashboard_Live_Header);

    public static string Dashboard_Live_Idle => ResourceManager.GetString(nameof(Dashboard_Live_Idle), Culture) ?? nameof(Dashboard_Live_Idle);

    public static string Dashboard_Live_Rt_On => ResourceManager.GetString(nameof(Dashboard_Live_Rt_On), Culture) ?? nameof(Dashboard_Live_Rt_On);

    public static string Dashboard_Live_Vram_Format => ResourceManager.GetString(nameof(Dashboard_Live_Vram_Format), Culture) ?? nameof(Dashboard_Live_Vram_Format);

    public static string Dashboard_Live_Waiting => ResourceManager.GetString(nameof(Dashboard_Live_Waiting), Culture) ?? nameof(Dashboard_Live_Waiting);

    public static string Dashboard_Recent_Header => ResourceManager.GetString(nameof(Dashboard_Recent_Header), Culture) ?? nameof(Dashboard_Recent_Header);

    public static string Dashboard_SessionDiscarded_Format => ResourceManager.GetString(nameof(Dashboard_SessionDiscarded_Format), Culture) ?? nameof(Dashboard_SessionDiscarded_Format);

    public static string Dashboard_SessionSaved_Format => ResourceManager.GetString(nameof(Dashboard_SessionSaved_Format), Culture) ?? nameof(Dashboard_SessionSaved_Format);

    public static string Dashboard_Totals_Games => ResourceManager.GetString(nameof(Dashboard_Totals_Games), Culture) ?? nameof(Dashboard_Totals_Games);

    public static string Dashboard_Totals_Playtime => ResourceManager.GetString(nameof(Dashboard_Totals_Playtime), Culture) ?? nameof(Dashboard_Totals_Playtime);

    public static string Dashboard_Totals_ThisWeek => ResourceManager.GetString(nameof(Dashboard_Totals_ThisWeek), Culture) ?? nameof(Dashboard_Totals_ThisWeek);

    public static string Diag_Written_Format => ResourceManager.GetString(nameof(Diag_Written_Format), Culture) ?? nameof(Diag_Written_Format);

    public static string EditGame_Detected => ResourceManager.GetString(nameof(EditGame_Detected), Culture) ?? nameof(EditGame_Detected);

    public static string EditGame_Name => ResourceManager.GetString(nameof(EditGame_Name), Culture) ?? nameof(EditGame_Name);

    public static string EditGame_Notes => ResourceManager.GetString(nameof(EditGame_Notes), Culture) ?? nameof(EditGame_Notes);

    public static string EditGame_Publisher => ResourceManager.GetString(nameof(EditGame_Publisher), Culture) ?? nameof(EditGame_Publisher);

    public static string EditGame_Save => ResourceManager.GetString(nameof(EditGame_Save), Culture) ?? nameof(EditGame_Save);

    public static string EditGame_Saved => ResourceManager.GetString(nameof(EditGame_Saved), Culture) ?? nameof(EditGame_Saved);

    public static string EditGame_Title => ResourceManager.GetString(nameof(EditGame_Title), Culture) ?? nameof(EditGame_Title);

    public static string EditGame_Version => ResourceManager.GetString(nameof(EditGame_Version), Culture) ?? nameof(EditGame_Version);

    public static string Exit_Crashed => ResourceManager.GetString(nameof(Exit_Crashed), Culture) ?? nameof(Exit_Crashed);

    public static string Exit_Degraded => ResourceManager.GetString(nameof(Exit_Degraded), Culture) ?? nameof(Exit_Degraded);

    public static string Exit_Interrupted => ResourceManager.GetString(nameof(Exit_Interrupted), Culture) ?? nameof(Exit_Interrupted);

    public static string Exit_Normal => ResourceManager.GetString(nameof(Exit_Normal), Culture) ?? nameof(Exit_Normal);

    public static string Exit_UnhookedSafety => ResourceManager.GetString(nameof(Exit_UnhookedSafety), Culture) ?? nameof(Exit_UnhookedSafety);

    public static string Fg_Active => ResourceManager.GetString(nameof(Fg_Active), Culture) ?? nameof(Fg_Active);

    public static string Fg_None => ResourceManager.GetString(nameof(Fg_None), Culture) ?? nameof(Fg_None);

    public static string Fg_Unknown => ResourceManager.GetString(nameof(Fg_Unknown), Culture) ?? nameof(Fg_Unknown);

    public static string Format_Duration_HoursMinutes_Format => ResourceManager.GetString(nameof(Format_Duration_HoursMinutes_Format), Culture) ?? nameof(Format_Duration_HoursMinutes_Format);

    public static string Format_Duration_MinutesSeconds_Format => ResourceManager.GetString(nameof(Format_Duration_MinutesSeconds_Format), Culture) ?? nameof(Format_Duration_MinutesSeconds_Format);

    public static string Format_Playtime_Hours_Format => ResourceManager.GetString(nameof(Format_Playtime_Hours_Format), Culture) ?? nameof(Format_Playtime_Hours_Format);

    public static string Format_Playtime_Minutes_Format => ResourceManager.GetString(nameof(Format_Playtime_Minutes_Format), Culture) ?? nameof(Format_Playtime_Minutes_Format);

    public static string Format_Resolution_Format => ResourceManager.GetString(nameof(Format_Resolution_Format), Culture) ?? nameof(Format_Resolution_Format);

    public static string Format_Resolution_Single_Format => ResourceManager.GetString(nameof(Format_Resolution_Single_Format), Culture) ?? nameof(Format_Resolution_Single_Format);

    public static string Format_Temperature_Format => ResourceManager.GetString(nameof(Format_Temperature_Format), Culture) ?? nameof(Format_Temperature_Format);

    public static string Fps_Census_NoRuntime => ResourceManager.GetString(nameof(Fps_Census_NoRuntime), Culture) ?? nameof(Fps_Census_NoRuntime);

    public static string Fps_Census_NoRuntime_Tooltip => ResourceManager.GetString(nameof(Fps_Census_NoRuntime_Tooltip), Culture) ?? nameof(Fps_Census_NoRuntime_Tooltip);

    public static string Fps_Census_NotRun => ResourceManager.GetString(nameof(Fps_Census_NotRun), Culture) ?? nameof(Fps_Census_NotRun);

    public static string Fps_Census_NotRun_Tooltip => ResourceManager.GetString(nameof(Fps_Census_NotRun_Tooltip), Culture) ?? nameof(Fps_Census_NotRun_Tooltip);

    public static string Fps_Census_RuntimeLoaded => ResourceManager.GetString(nameof(Fps_Census_RuntimeLoaded), Culture) ?? nameof(Fps_Census_RuntimeLoaded);

    public static string Fps_Census_RuntimeLoaded_Tooltip => ResourceManager.GetString(nameof(Fps_Census_RuntimeLoaded_Tooltip), Culture) ?? nameof(Fps_Census_RuntimeLoaded_Tooltip);

    public static string Fps_Census_Withheld => ResourceManager.GetString(nameof(Fps_Census_Withheld), Culture) ?? nameof(Fps_Census_Withheld);

    public static string Fps_Census_Withheld_Tooltip => ResourceManager.GetString(nameof(Fps_Census_Withheld_Tooltip), Culture) ?? nameof(Fps_Census_Withheld_Tooltip);

    public static string Fps_Fg_Chip_Format => ResourceManager.GetString(nameof(Fps_Fg_Chip_Format), Culture) ?? nameof(Fps_Fg_Chip_Format);

    public static string Fps_Fg_Format => ResourceManager.GetString(nameof(Fps_Fg_Format), Culture) ?? nameof(Fps_Fg_Format);

    public static string Fps_Native_Tooltip => ResourceManager.GetString(nameof(Fps_Native_Tooltip), Culture) ?? nameof(Fps_Native_Tooltip);

    public static string Fps_None_Tooltip => ResourceManager.GetString(nameof(Fps_None_Tooltip), Culture) ?? nameof(Fps_None_Tooltip);

    public static string Fps_Presented_Format => ResourceManager.GetString(nameof(Fps_Presented_Format), Culture) ?? nameof(Fps_Presented_Format);

    public static string GameDetail_Back => ResourceManager.GetString(nameof(GameDetail_Back), Culture) ?? nameof(GameDetail_Back);

    public static string GameDetail_Edit => ResourceManager.GetString(nameof(GameDetail_Edit), Culture) ?? nameof(GameDetail_Edit);

    public static string GameDetail_Hooking_Body => ResourceManager.GetString(nameof(GameDetail_Hooking_Body), Culture) ?? nameof(GameDetail_Hooking_Body);

    public static string GameDetail_Hooking_Busy => ResourceManager.GetString(nameof(GameDetail_Hooking_Busy), Culture) ?? nameof(GameDetail_Hooking_Busy);

    public static string GameDetail_Hooking_Header => ResourceManager.GetString(nameof(GameDetail_Hooking_Header), Culture) ?? nameof(GameDetail_Hooking_Header);

    public static string GameDetail_Hooking_Off => ResourceManager.GetString(nameof(GameDetail_Hooking_Off), Culture) ?? nameof(GameDetail_Hooking_Off);

    public static string GameDetail_Hooking_On => ResourceManager.GetString(nameof(GameDetail_Hooking_On), Culture) ?? nameof(GameDetail_Hooking_On);

    public static string GameDetail_Hooking_ReEnable => ResourceManager.GetString(nameof(GameDetail_Hooking_ReEnable), Culture) ?? nameof(GameDetail_Hooking_ReEnable);

    public static string GameDetail_Hooking_Unverified => ResourceManager.GetString(nameof(GameDetail_Hooking_Unverified), Culture) ?? nameof(GameDetail_Hooking_Unverified);

    public static string GameDetail_LastSession_Format => ResourceManager.GetString(nameof(GameDetail_LastSession_Format), Culture) ?? nameof(GameDetail_LastSession_Format);

    public static string GameDetail_LifetimeAvg => ResourceManager.GetString(nameof(GameDetail_LifetimeAvg), Culture) ?? nameof(GameDetail_LifetimeAvg);

    public static string GameDetail_Measured_Empty => ResourceManager.GetString(nameof(GameDetail_Measured_Empty), Culture) ?? nameof(GameDetail_Measured_Empty);

    public static string GameDetail_Measured_Header => ResourceManager.GetString(nameof(GameDetail_Measured_Header), Culture) ?? nameof(GameDetail_Measured_Header);

    public static string GameDetail_Measured_NotHooked => ResourceManager.GetString(nameof(GameDetail_Measured_NotHooked), Culture) ?? nameof(GameDetail_Measured_NotHooked);

    public static string GameDetail_NotFound => ResourceManager.GetString(nameof(GameDetail_NotFound), Culture) ?? nameof(GameDetail_NotFound);

    public static string GameDetail_Remove => ResourceManager.GetString(nameof(GameDetail_Remove), Culture) ?? nameof(GameDetail_Remove);

    public static string GameDetail_Sessions_Empty => ResourceManager.GetString(nameof(GameDetail_Sessions_Empty), Culture) ?? nameof(GameDetail_Sessions_Empty);

    public static string GameDetail_Supports_Empty => ResourceManager.GetString(nameof(GameDetail_Supports_Empty), Culture) ?? nameof(GameDetail_Supports_Empty);

    public static string GameDetail_Supports_Format => ResourceManager.GetString(nameof(GameDetail_Supports_Format), Culture) ?? nameof(GameDetail_Supports_Format);

    public static string GameDetail_Supports_Header => ResourceManager.GetString(nameof(GameDetail_Supports_Header), Culture) ?? nameof(GameDetail_Supports_Header);

    public static string GameDetail_Tab_Distribution => ResourceManager.GetString(nameof(GameDetail_Tab_Distribution), Culture) ?? nameof(GameDetail_Tab_Distribution);

    public static string GameDetail_Tab_Frametime => ResourceManager.GetString(nameof(GameDetail_Tab_Frametime), Culture) ?? nameof(GameDetail_Tab_Frametime);

    public static string GameDetail_Tab_Latency => ResourceManager.GetString(nameof(GameDetail_Tab_Latency), Culture) ?? nameof(GameDetail_Tab_Latency);

    public static string GameDetail_Tab_Later_Format => ResourceManager.GetString(nameof(GameDetail_Tab_Later_Format), Culture) ?? nameof(GameDetail_Tab_Later_Format);

    public static string GameDetail_Tab_Sensors => ResourceManager.GetString(nameof(GameDetail_Tab_Sensors), Culture) ?? nameof(GameDetail_Tab_Sensors);

    public static string GameDetail_Tab_Sessions => ResourceManager.GetString(nameof(GameDetail_Tab_Sessions), Culture) ?? nameof(GameDetail_Tab_Sessions);

    public static string GameDetail_Tab_Trend => ResourceManager.GetString(nameof(GameDetail_Tab_Trend), Culture) ?? nameof(GameDetail_Tab_Trend);

    public static string Games_Add => ResourceManager.GetString(nameof(Games_Add), Culture) ?? nameof(Games_Add);

    public static string Games_Card_HookOff => ResourceManager.GetString(nameof(Games_Card_HookOff), Culture) ?? nameof(Games_Card_HookOff);

    public static string Games_Card_HookOn => ResourceManager.GetString(nameof(Games_Card_HookOn), Culture) ?? nameof(Games_Card_HookOn);

    public static string Games_Card_LastPlayed_Format => ResourceManager.GetString(nameof(Games_Card_LastPlayed_Format), Culture) ?? nameof(Games_Card_LastPlayed_Format);

    public static string Games_Card_NeverPlayed => ResourceManager.GetString(nameof(Games_Card_NeverPlayed), Culture) ?? nameof(Games_Card_NeverPlayed);

    public static string Games_Card_Playtime_Format => ResourceManager.GetString(nameof(Games_Card_Playtime_Format), Culture) ?? nameof(Games_Card_Playtime_Format);

    public static string Games_Card_Sessions_Format => ResourceManager.GetString(nameof(Games_Card_Sessions_Format), Culture) ?? nameof(Games_Card_Sessions_Format);

    public static string Games_Empty => ResourceManager.GetString(nameof(Games_Empty), Culture) ?? nameof(Games_Empty);

    public static string Games_Header => ResourceManager.GetString(nameof(Games_Header), Culture) ?? nameof(Games_Header);

    public static string Games_NoMatch => ResourceManager.GetString(nameof(Games_NoMatch), Culture) ?? nameof(Games_NoMatch);

    public static string Games_Search_Placeholder => ResourceManager.GetString(nameof(Games_Search_Placeholder), Culture) ?? nameof(Games_Search_Placeholder);

    public static string Games_Sort_Label => ResourceManager.GetString(nameof(Games_Sort_Label), Culture) ?? nameof(Games_Sort_Label);

    public static string Games_Sort_LastPlayed => ResourceManager.GetString(nameof(Games_Sort_LastPlayed), Culture) ?? nameof(Games_Sort_LastPlayed);

    public static string Games_Sort_Name => ResourceManager.GetString(nameof(Games_Sort_Name), Culture) ?? nameof(Games_Sort_Name);

    public static string Games_Sort_Playtime => ResourceManager.GetString(nameof(Games_Sort_Playtime), Culture) ?? nameof(Games_Sort_Playtime);

    public static string Latency_Avg => ResourceManager.GetString(nameof(Latency_Avg), Culture) ?? nameof(Latency_Avg);

    public static string Latency_Axis => ResourceManager.GetString(nameof(Latency_Axis), Culture) ?? nameof(Latency_Axis);

    public static string Latency_Empty => ResourceManager.GetString(nameof(Latency_Empty), Culture) ?? nameof(Latency_Empty);

    public static string Latency_Header => ResourceManager.GetString(nameof(Latency_Header), Culture) ?? nameof(Latency_Header);

    public static string Latency_P95 => ResourceManager.GetString(nameof(Latency_P95), Culture) ?? nameof(Latency_P95);

    public static string Latency_Series => ResourceManager.GetString(nameof(Latency_Series), Culture) ?? nameof(Latency_Series);

    public static string Latency_Stats_Format => ResourceManager.GetString(nameof(Latency_Stats_Format), Culture) ?? nameof(Latency_Stats_Format);

    public static string Logs_Bundle_Exported_Format => ResourceManager.GetString(nameof(Logs_Bundle_Exported_Format), Culture) ?? nameof(Logs_Bundle_Exported_Format);

    public static string Logs_Bundle_Failed_Format => ResourceManager.GetString(nameof(Logs_Bundle_Failed_Format), Culture) ?? nameof(Logs_Bundle_Failed_Format);

    public static string Logs_Empty => ResourceManager.GetString(nameof(Logs_Empty), Culture) ?? nameof(Logs_Empty);

    public static string Logs_ExportBundle => ResourceManager.GetString(nameof(Logs_ExportBundle), Culture) ?? nameof(Logs_ExportBundle);

    public static string Logs_Header => ResourceManager.GetString(nameof(Logs_Header), Culture) ?? nameof(Logs_Header);

    public static string Logs_Level_All => ResourceManager.GetString(nameof(Logs_Level_All), Culture) ?? nameof(Logs_Level_All);

    public static string Logs_Level_Error => ResourceManager.GetString(nameof(Logs_Level_Error), Culture) ?? nameof(Logs_Level_Error);

    public static string Logs_Level_Warning => ResourceManager.GetString(nameof(Logs_Level_Warning), Culture) ?? nameof(Logs_Level_Warning);

    public static string Logs_OpenFolder => ResourceManager.GetString(nameof(Logs_OpenFolder), Culture) ?? nameof(Logs_OpenFolder);

    public static string Logs_Pause => ResourceManager.GetString(nameof(Logs_Pause), Culture) ?? nameof(Logs_Pause);

    public static string Logs_Search_Placeholder => ResourceManager.GetString(nameof(Logs_Search_Placeholder), Culture) ?? nameof(Logs_Search_Placeholder);

    public static string Logs_Showing_Format => ResourceManager.GetString(nameof(Logs_Showing_Format), Culture) ?? nameof(Logs_Showing_Format);

    public static string Logs_Source_Agent => ResourceManager.GetString(nameof(Logs_Source_Agent), Culture) ?? nameof(Logs_Source_Agent);

    public static string Logs_Source_Ui => ResourceManager.GetString(nameof(Logs_Source_Ui), Culture) ?? nameof(Logs_Source_Ui);

    public static string Menu_File => ResourceManager.GetString(nameof(Menu_File), Culture) ?? nameof(Menu_File);

    public static string Menu_File_AddGame => ResourceManager.GetString(nameof(Menu_File_AddGame), Culture) ?? nameof(Menu_File_AddGame);

    public static string Menu_File_Exit => ResourceManager.GetString(nameof(Menu_File_Exit), Culture) ?? nameof(Menu_File_Exit);

    public static string Menu_File_Export => ResourceManager.GetString(nameof(Menu_File_Export), Culture) ?? nameof(Menu_File_Export);

    public static string Menu_File_ImportLibrary => ResourceManager.GetString(nameof(Menu_File_ImportLibrary), Culture) ?? nameof(Menu_File_ImportLibrary);

    public static string Menu_Help => ResourceManager.GetString(nameof(Menu_Help), Culture) ?? nameof(Menu_Help);

    public static string Menu_Help_About => ResourceManager.GetString(nameof(Menu_Help_About), Culture) ?? nameof(Menu_Help_About);

    public static string Menu_Help_CheckUpdates => ResourceManager.GetString(nameof(Menu_Help_CheckUpdates), Culture) ?? nameof(Menu_Help_CheckUpdates);

    public static string Menu_Help_Documentation => ResourceManager.GetString(nameof(Menu_Help_Documentation), Culture) ?? nameof(Menu_Help_Documentation);

    public static string Menu_Help_ReportBug => ResourceManager.GetString(nameof(Menu_Help_ReportBug), Culture) ?? nameof(Menu_Help_ReportBug);

    public static string Menu_Tools => ResourceManager.GetString(nameof(Menu_Tools), Culture) ?? nameof(Menu_Tools);

    public static string Menu_Tools_AgentStatus => ResourceManager.GetString(nameof(Menu_Tools_AgentStatus), Culture) ?? nameof(Menu_Tools_AgentStatus);

    public static string Menu_Tools_DbMaintenance => ResourceManager.GetString(nameof(Menu_Tools_DbMaintenance), Culture) ?? nameof(Menu_Tools_DbMaintenance);

    public static string Menu_Tools_OpenDataFolder => ResourceManager.GetString(nameof(Menu_Tools_OpenDataFolder), Culture) ?? nameof(Menu_Tools_OpenDataFolder);

    public static string Menu_Tools_UpdateRules => ResourceManager.GetString(nameof(Menu_Tools_UpdateRules), Culture) ?? nameof(Menu_Tools_UpdateRules);

    public static string Menu_Tools_VulkanLayer => ResourceManager.GetString(nameof(Menu_Tools_VulkanLayer), Culture) ?? nameof(Menu_Tools_VulkanLayer);

    public static string Nav_Compare => ResourceManager.GetString(nameof(Nav_Compare), Culture) ?? nameof(Nav_Compare);

    public static string Nav_Dashboard => ResourceManager.GetString(nameof(Nav_Dashboard), Culture) ?? nameof(Nav_Dashboard);

    public static string Nav_Games => ResourceManager.GetString(nameof(Nav_Games), Culture) ?? nameof(Nav_Games);

    public static string Nav_Logs => ResourceManager.GetString(nameof(Nav_Logs), Culture) ?? nameof(Nav_Logs);

    public static string Nav_Settings => ResourceManager.GetString(nameof(Nav_Settings), Culture) ?? nameof(Nav_Settings);

    public static string Notice_Degraded_Body_Format => ResourceManager.GetString(nameof(Notice_Degraded_Body_Format), Culture) ?? nameof(Notice_Degraded_Body_Format);

    public static string Notice_Degraded_Title => ResourceManager.GetString(nameof(Notice_Degraded_Title), Culture) ?? nameof(Notice_Degraded_Title);

    public static string Notice_Dismiss => ResourceManager.GetString(nameof(Notice_Dismiss), Culture) ?? nameof(Notice_Dismiss);

    public static string Notice_Error_Title => ResourceManager.GetString(nameof(Notice_Error_Title), Culture) ?? nameof(Notice_Error_Title);

    public static string Notice_Refused_Recording => ResourceManager.GetString(nameof(Notice_Refused_Recording), Culture) ?? nameof(Notice_Refused_Recording);

    public static string Notice_Refused_Title_Format => ResourceManager.GetString(nameof(Notice_Refused_Title_Format), Culture) ?? nameof(Notice_Refused_Title_Format);

    public static string Notice_Unhooked_Title => ResourceManager.GetString(nameof(Notice_Unhooked_Title), Culture) ?? nameof(Notice_Unhooked_Title);

    public static string NotYet_Body => ResourceManager.GetString(nameof(NotYet_Body), Culture) ?? nameof(NotYet_Body);

    public static string NotYet_Title => ResourceManager.GetString(nameof(NotYet_Title), Culture) ?? nameof(NotYet_Title);

    public static string Override_Apply => ResourceManager.GetString(nameof(Override_Apply), Culture) ?? nameof(Override_Apply);

    public static string Override_Body => ResourceManager.GetString(nameof(Override_Body), Culture) ?? nameof(Override_Body);

    public static string Override_Default => ResourceManager.GetString(nameof(Override_Default), Culture) ?? nameof(Override_Default);

    public static string Override_Keep => ResourceManager.GetString(nameof(Override_Keep), Culture) ?? nameof(Override_Keep);

    public static string Override_Title_Format => ResourceManager.GetString(nameof(Override_Title_Format), Culture) ?? nameof(Override_Title_Format);

    public static string RemoveGame_Body => ResourceManager.GetString(nameof(RemoveGame_Body), Culture) ?? nameof(RemoveGame_Body);

    public static string RemoveGame_Delete => ResourceManager.GetString(nameof(RemoveGame_Delete), Culture) ?? nameof(RemoveGame_Delete);

    public static string RemoveGame_Keep => ResourceManager.GetString(nameof(RemoveGame_Keep), Culture) ?? nameof(RemoveGame_Keep);

    public static string RemoveGame_Removed_Format => ResourceManager.GetString(nameof(RemoveGame_Removed_Format), Culture) ?? nameof(RemoveGame_Removed_Format);

    public static string RemoveGame_Title_Format => ResourceManager.GetString(nameof(RemoveGame_Title_Format), Culture) ?? nameof(RemoveGame_Title_Format);

    public static string Sensors_Axis_Mb => ResourceManager.GetString(nameof(Sensors_Axis_Mb), Culture) ?? nameof(Sensors_Axis_Mb);

    public static string Sensors_Empty => ResourceManager.GetString(nameof(Sensors_Empty), Culture) ?? nameof(Sensors_Empty);

    public static string Sensors_Series_GpuHotspot => ResourceManager.GetString(nameof(Sensors_Series_GpuHotspot), Culture) ?? nameof(Sensors_Series_GpuHotspot);

    public static string Sensors_Series_GpuLoad => ResourceManager.GetString(nameof(Sensors_Series_GpuLoad), Culture) ?? nameof(Sensors_Series_GpuLoad);

    public static string Sensors_Series_GpuPower => ResourceManager.GetString(nameof(Sensors_Series_GpuPower), Culture) ?? nameof(Sensors_Series_GpuPower);

    public static string Sensors_Series_GpuTemp => ResourceManager.GetString(nameof(Sensors_Series_GpuTemp), Culture) ?? nameof(Sensors_Series_GpuTemp);

    public static string Sensors_Series_VramAdapter => ResourceManager.GetString(nameof(Sensors_Series_VramAdapter), Culture) ?? nameof(Sensors_Series_VramAdapter);

    public static string Sensors_Series_VramProcess => ResourceManager.GetString(nameof(Sensors_Series_VramProcess), Culture) ?? nameof(Sensors_Series_VramProcess);

    public static string Sensors_Temps_Header => ResourceManager.GetString(nameof(Sensors_Temps_Header), Culture) ?? nameof(Sensors_Temps_Header);

    public static string Sensors_Vram_Header => ResourceManager.GetString(nameof(Sensors_Vram_Header), Culture) ?? nameof(Sensors_Vram_Header);

    public static string Sessions_Col_Api => ResourceManager.GetString(nameof(Sessions_Col_Api), Culture) ?? nameof(Sessions_Col_Api);

    public static string Sessions_Col_Date => ResourceManager.GetString(nameof(Sessions_Col_Date), Culture) ?? nameof(Sessions_Col_Date);

    public static string Sessions_Col_Displayed => ResourceManager.GetString(nameof(Sessions_Col_Displayed), Culture) ?? nameof(Sessions_Col_Displayed);

    public static string Sessions_Col_Duration => ResourceManager.GetString(nameof(Sessions_Col_Duration), Culture) ?? nameof(Sessions_Col_Duration);

    public static string Sessions_Col_Exit => ResourceManager.GetString(nameof(Sessions_Col_Exit), Culture) ?? nameof(Sessions_Col_Exit);

    public static string Sessions_Col_Fg => ResourceManager.GetString(nameof(Sessions_Col_Fg), Culture) ?? nameof(Sessions_Col_Fg);

    public static string Sessions_Col_GpuTemp => ResourceManager.GetString(nameof(Sessions_Col_GpuTemp), Culture) ?? nameof(Sessions_Col_GpuTemp);

    public static string Sessions_Col_Native => ResourceManager.GetString(nameof(Sessions_Col_Native), Culture) ?? nameof(Sessions_Col_Native);

    public static string Sessions_Col_P01Low => ResourceManager.GetString(nameof(Sessions_Col_P01Low), Culture) ?? nameof(Sessions_Col_P01Low);

    public static string Sessions_Col_P1Low => ResourceManager.GetString(nameof(Sessions_Col_P1Low), Culture) ?? nameof(Sessions_Col_P1Low);

    public static string Sessions_Col_Resolution => ResourceManager.GetString(nameof(Sessions_Col_Resolution), Culture) ?? nameof(Sessions_Col_Resolution);

    public static string Sessions_Col_Tags => ResourceManager.GetString(nameof(Sessions_Col_Tags), Culture) ?? nameof(Sessions_Col_Tags);

    public static string Sessions_Col_Tier => ResourceManager.GetString(nameof(Sessions_Col_Tier), Culture) ?? nameof(Sessions_Col_Tier);

    public static string Settings_Agent_Elevated => ResourceManager.GetString(nameof(Settings_Agent_Elevated), Culture) ?? nameof(Settings_Agent_Elevated);

    public static string Settings_Agent_Elevation_Body => ResourceManager.GetString(nameof(Settings_Agent_Elevation_Body), Culture) ?? nameof(Settings_Agent_Elevation_Body);

    public static string Settings_Agent_Elevation_Label => ResourceManager.GetString(nameof(Settings_Agent_Elevation_Label), Culture) ?? nameof(Settings_Agent_Elevation_Label);

    public static string Settings_Agent_Header => ResourceManager.GetString(nameof(Settings_Agent_Header), Culture) ?? nameof(Settings_Agent_Header);

    public static string Settings_Agent_NotElevated => ResourceManager.GetString(nameof(Settings_Agent_NotElevated), Culture) ?? nameof(Settings_Agent_NotElevated);

    public static string Settings_Agent_Task_Label => ResourceManager.GetString(nameof(Settings_Agent_Task_Label), Culture) ?? nameof(Settings_Agent_Task_Label);

    public static string Settings_Agent_Task_Later => ResourceManager.GetString(nameof(Settings_Agent_Task_Later), Culture) ?? nameof(Settings_Agent_Task_Later);

    public static string Settings_Appearance_Header => ResourceManager.GetString(nameof(Settings_Appearance_Header), Culture) ?? nameof(Settings_Appearance_Header);

    public static string Settings_Applied => ResourceManager.GetString(nameof(Settings_Applied), Culture) ?? nameof(Settings_Applied);

    public static string Settings_Background_Body => ResourceManager.GetString(nameof(Settings_Background_Body), Culture) ?? nameof(Settings_Background_Body);

    public static string Settings_Background_Label => ResourceManager.GetString(nameof(Settings_Background_Label), Culture) ?? nameof(Settings_Background_Label);

    public static string Settings_Capture_Header => ResourceManager.GetString(nameof(Settings_Capture_Header), Culture) ?? nameof(Settings_Capture_Header);

    public static string Settings_Channel_Beta => ResourceManager.GetString(nameof(Settings_Channel_Beta), Culture) ?? nameof(Settings_Channel_Beta);

    public static string Settings_Channel_Stable => ResourceManager.GetString(nameof(Settings_Channel_Stable), Culture) ?? nameof(Settings_Channel_Stable);

    public static string Settings_Header => ResourceManager.GetString(nameof(Settings_Header), Culture) ?? nameof(Settings_Header);

    public static string Settings_HookedGames_Empty => ResourceManager.GetString(nameof(Settings_HookedGames_Empty), Culture) ?? nameof(Settings_HookedGames_Empty);

    public static string Settings_HookedGames_Label => ResourceManager.GetString(nameof(Settings_HookedGames_Label), Culture) ?? nameof(Settings_HookedGames_Label);

    public static string Settings_HookedGames_Revoke => ResourceManager.GetString(nameof(Settings_HookedGames_Revoke), Culture) ?? nameof(Settings_HookedGames_Revoke);

    public static string Settings_Interval_Body => ResourceManager.GetString(nameof(Settings_Interval_Body), Culture) ?? nameof(Settings_Interval_Body);

    public static string Settings_Interval_Label => ResourceManager.GetString(nameof(Settings_Interval_Label), Culture) ?? nameof(Settings_Interval_Label);

    public static string Settings_Invalid_Format => ResourceManager.GetString(nameof(Settings_Invalid_Format), Culture) ?? nameof(Settings_Invalid_Format);

    public static string Settings_KillSwitch_Body => ResourceManager.GetString(nameof(Settings_KillSwitch_Body), Culture) ?? nameof(Settings_KillSwitch_Body);

    public static string Settings_KillSwitch_Label => ResourceManager.GetString(nameof(Settings_KillSwitch_Label), Culture) ?? nameof(Settings_KillSwitch_Label);

    public static string Settings_KillSwitch_Off => ResourceManager.GetString(nameof(Settings_KillSwitch_Off), Culture) ?? nameof(Settings_KillSwitch_Off);

    public static string Settings_KillSwitch_On => ResourceManager.GetString(nameof(Settings_KillSwitch_On), Culture) ?? nameof(Settings_KillSwitch_On);

    public static string Settings_Language_Label => ResourceManager.GetString(nameof(Settings_Language_Label), Culture) ?? nameof(Settings_Language_Label);

    public static string Settings_Language_Note => ResourceManager.GetString(nameof(Settings_Language_Note), Culture) ?? nameof(Settings_Language_Note);

    public static string Settings_Legal_Header => ResourceManager.GetString(nameof(Settings_Legal_Header), Culture) ?? nameof(Settings_Legal_Header);

    public static string Settings_Legal_Reopen => ResourceManager.GetString(nameof(Settings_Legal_Reopen), Culture) ?? nameof(Settings_Legal_Reopen);

    public static string Settings_LogDebug_Body => ResourceManager.GetString(nameof(Settings_LogDebug_Body), Culture) ?? nameof(Settings_LogDebug_Body);

    public static string Settings_LogDebug_Label => ResourceManager.GetString(nameof(Settings_LogDebug_Label), Culture) ?? nameof(Settings_LogDebug_Label);

    public static string Settings_Logging_Header => ResourceManager.GetString(nameof(Settings_Logging_Header), Culture) ?? nameof(Settings_Logging_Header);

    public static string Settings_MinimizeToTray_Label => ResourceManager.GetString(nameof(Settings_MinimizeToTray_Label), Culture) ?? nameof(Settings_MinimizeToTray_Label);

    public static string Settings_MinimizeToTray_Later => ResourceManager.GetString(nameof(Settings_MinimizeToTray_Later), Culture) ?? nameof(Settings_MinimizeToTray_Later);

    public static string Settings_MinSession_Body => ResourceManager.GetString(nameof(Settings_MinSession_Body), Culture) ?? nameof(Settings_MinSession_Body);

    public static string Settings_MinSession_Label => ResourceManager.GetString(nameof(Settings_MinSession_Label), Culture) ?? nameof(Settings_MinSession_Label);

    public static string Settings_OnlineMetadata_Body => ResourceManager.GetString(nameof(Settings_OnlineMetadata_Body), Culture) ?? nameof(Settings_OnlineMetadata_Body);

    public static string Settings_OnlineMetadata_Label => ResourceManager.GetString(nameof(Settings_OnlineMetadata_Label), Culture) ?? nameof(Settings_OnlineMetadata_Label);

    public static string Settings_Policy_Header => ResourceManager.GetString(nameof(Settings_Policy_Header), Culture) ?? nameof(Settings_Policy_Header);

    public static string Settings_Privacy_Header => ResourceManager.GetString(nameof(Settings_Privacy_Header), Culture) ?? nameof(Settings_Privacy_Header);

    public static string Settings_Retention_Body => ResourceManager.GetString(nameof(Settings_Retention_Body), Culture) ?? nameof(Settings_Retention_Body);

    public static string Settings_Retention_Label => ResourceManager.GetString(nameof(Settings_Retention_Label), Culture) ?? nameof(Settings_Retention_Label);

    public static string Settings_SafetyDocs => ResourceManager.GetString(nameof(Settings_SafetyDocs), Culture) ?? nameof(Settings_SafetyDocs);

    public static string Settings_StartWithWindows_Body => ResourceManager.GetString(nameof(Settings_StartWithWindows_Body), Culture) ?? nameof(Settings_StartWithWindows_Body);

    public static string Settings_StartWithWindows_Label => ResourceManager.GetString(nameof(Settings_StartWithWindows_Label), Culture) ?? nameof(Settings_StartWithWindows_Label);

    public static string Settings_Theme_Dark => ResourceManager.GetString(nameof(Settings_Theme_Dark), Culture) ?? nameof(Settings_Theme_Dark);

    public static string Settings_Theme_Label => ResourceManager.GetString(nameof(Settings_Theme_Label), Culture) ?? nameof(Settings_Theme_Label);

    public static string Settings_Theme_Light => ResourceManager.GetString(nameof(Settings_Theme_Light), Culture) ?? nameof(Settings_Theme_Light);

    public static string Settings_Theme_System => ResourceManager.GetString(nameof(Settings_Theme_System), Culture) ?? nameof(Settings_Theme_System);

    public static string Settings_UpdateChannel_Body => ResourceManager.GetString(nameof(Settings_UpdateChannel_Body), Culture) ?? nameof(Settings_UpdateChannel_Body);

    public static string Settings_UpdateChannel_Label => ResourceManager.GetString(nameof(Settings_UpdateChannel_Label), Culture) ?? nameof(Settings_UpdateChannel_Label);

    public static string Settings_Updates_Header => ResourceManager.GetString(nameof(Settings_Updates_Header), Culture) ?? nameof(Settings_Updates_Header);

    public static string Settings_VkLayer_Label => ResourceManager.GetString(nameof(Settings_VkLayer_Label), Culture) ?? nameof(Settings_VkLayer_Label);

    public static string Settings_VkLayer_NotRegistered => ResourceManager.GetString(nameof(Settings_VkLayer_NotRegistered), Culture) ?? nameof(Settings_VkLayer_NotRegistered);

    public static string Settings_VkLayer_Registered => ResourceManager.GetString(nameof(Settings_VkLayer_Registered), Culture) ?? nameof(Settings_VkLayer_Registered);

    public static string Settings_VkLayer_Unknown => ResourceManager.GetString(nameof(Settings_VkLayer_Unknown), Culture) ?? nameof(Settings_VkLayer_Unknown);

    public static string Settings_Window_Header => ResourceManager.GetString(nameof(Settings_Window_Header), Culture) ?? nameof(Settings_Window_Header);

    public static string Summary_Annotations_Header => ResourceManager.GetString(nameof(Summary_Annotations_Header), Culture) ?? nameof(Summary_Annotations_Header);

    public static string Summary_Crash_Body => ResourceManager.GetString(nameof(Summary_Crash_Body), Culture) ?? nameof(Summary_Crash_Body);

    public static string Summary_Crash_Title => ResourceManager.GetString(nameof(Summary_Crash_Title), Culture) ?? nameof(Summary_Crash_Title);

    public static string Summary_Distribution_Header => ResourceManager.GetString(nameof(Summary_Distribution_Header), Culture) ?? nameof(Summary_Distribution_Header);

    public static string Summary_Export_Csv => ResourceManager.GetString(nameof(Summary_Export_Csv), Culture) ?? nameof(Summary_Export_Csv);

    public static string Summary_Export_Failed_Format => ResourceManager.GetString(nameof(Summary_Export_Failed_Format), Culture) ?? nameof(Summary_Export_Failed_Format);

    public static string Summary_Export_Json => ResourceManager.GetString(nameof(Summary_Export_Json), Culture) ?? nameof(Summary_Export_Json);

    public static string Summary_Export_Png => ResourceManager.GetString(nameof(Summary_Export_Png), Culture) ?? nameof(Summary_Export_Png);

    public static string Summary_Export_Tier2 => ResourceManager.GetString(nameof(Summary_Export_Tier2), Culture) ?? nameof(Summary_Export_Tier2);

    public static string Summary_Exported_Format => ResourceManager.GetString(nameof(Summary_Exported_Format), Culture) ?? nameof(Summary_Exported_Format);

    public static string Summary_Frametime_Header => ResourceManager.GetString(nameof(Summary_Frametime_Header), Culture) ?? nameof(Summary_Frametime_Header);

    public static string Summary_Line_Format => ResourceManager.GetString(nameof(Summary_Line_Format), Culture) ?? nameof(Summary_Line_Format);

    public static string Summary_Lows_Presented => ResourceManager.GetString(nameof(Summary_Lows_Presented), Culture) ?? nameof(Summary_Lows_Presented);

    public static string Summary_Notes_Placeholder => ResourceManager.GetString(nameof(Summary_Notes_Placeholder), Culture) ?? nameof(Summary_Notes_Placeholder);

    public static string Summary_NotFound => ResourceManager.GetString(nameof(Summary_NotFound), Culture) ?? nameof(Summary_NotFound);

    public static string Summary_Open => ResourceManager.GetString(nameof(Summary_Open), Culture) ?? nameof(Summary_Open);

    public static string Summary_Save => ResourceManager.GetString(nameof(Summary_Save), Culture) ?? nameof(Summary_Save);

    public static string Summary_Saved => ResourceManager.GetString(nameof(Summary_Saved), Culture) ?? nameof(Summary_Saved);

    public static string Summary_Show_Displayed => ResourceManager.GetString(nameof(Summary_Show_Displayed), Culture) ?? nameof(Summary_Show_Displayed);

    public static string Summary_Show_Sensors => ResourceManager.GetString(nameof(Summary_Show_Sensors), Culture) ?? nameof(Summary_Show_Sensors);

    public static string Summary_Stat_Avg => ResourceManager.GetString(nameof(Summary_Stat_Avg), Culture) ?? nameof(Summary_Stat_Avg);

    public static string Summary_Stat_Duration => ResourceManager.GetString(nameof(Summary_Stat_Duration), Culture) ?? nameof(Summary_Stat_Duration);

    public static string Summary_Stat_Median => ResourceManager.GetString(nameof(Summary_Stat_Median), Culture) ?? nameof(Summary_Stat_Median);

    public static string Summary_Stat_MinMax => ResourceManager.GetString(nameof(Summary_Stat_MinMax), Culture) ?? nameof(Summary_Stat_MinMax);

    public static string Summary_Stat_MinMax_Format => ResourceManager.GetString(nameof(Summary_Stat_MinMax_Format), Culture) ?? nameof(Summary_Stat_MinMax_Format);

    public static string Summary_Stat_P01Low => ResourceManager.GetString(nameof(Summary_Stat_P01Low), Culture) ?? nameof(Summary_Stat_P01Low);

    public static string Summary_Stat_P1Low => ResourceManager.GetString(nameof(Summary_Stat_P1Low), Culture) ?? nameof(Summary_Stat_P1Low);

    public static string Summary_Stat_StdDev => ResourceManager.GetString(nameof(Summary_Stat_StdDev), Culture) ?? nameof(Summary_Stat_StdDev);

    public static string Summary_Stat_StdDev_Format => ResourceManager.GetString(nameof(Summary_Stat_StdDev_Format), Culture) ?? nameof(Summary_Stat_StdDev_Format);

    public static string Summary_Stat_Stutter => ResourceManager.GetString(nameof(Summary_Stat_Stutter), Culture) ?? nameof(Summary_Stat_Stutter);

    public static string Summary_Stat_Stutter_Format => ResourceManager.GetString(nameof(Summary_Stat_Stutter_Format), Culture) ?? nameof(Summary_Stat_Stutter_Format);

    public static string Summary_Tags_Placeholder => ResourceManager.GetString(nameof(Summary_Tags_Placeholder), Culture) ?? nameof(Summary_Tags_Placeholder);

    public static string Summary_Tier2_Body => ResourceManager.GetString(nameof(Summary_Tier2_Body), Culture) ?? nameof(Summary_Tier2_Body);

    public static string Summary_Title_Format => ResourceManager.GetString(nameof(Summary_Title_Format), Culture) ?? nameof(Summary_Title_Format);

    public static string Summary_Unhooked_Body => ResourceManager.GetString(nameof(Summary_Unhooked_Body), Culture) ?? nameof(Summary_Unhooked_Body);

    public static string Summary_Unhooked_Title => ResourceManager.GetString(nameof(Summary_Unhooked_Title), Culture) ?? nameof(Summary_Unhooked_Title);

    public static string Tabs_SelectASession => ResourceManager.GetString(nameof(Tabs_SelectASession), Culture) ?? nameof(Tabs_SelectASession);

    public static string Tabs_SelectedNoFrames => ResourceManager.GetString(nameof(Tabs_SelectedNoFrames), Culture) ?? nameof(Tabs_SelectedNoFrames);

    public static string Tabs_SelectedNotHooked => ResourceManager.GetString(nameof(Tabs_SelectedNotHooked), Culture) ?? nameof(Tabs_SelectedNotHooked);

    public static string Tier_Dash_Tooltip => ResourceManager.GetString(nameof(Tier_Dash_Tooltip), Culture) ?? nameof(Tier_Dash_Tooltip);

    public static string Tier_Hooked => ResourceManager.GetString(nameof(Tier_Hooked), Culture) ?? nameof(Tier_Hooked);

    public static string Tier_Hooked_Tooltip => ResourceManager.GetString(nameof(Tier_Hooked_Tooltip), Culture) ?? nameof(Tier_Hooked_Tooltip);

    public static string Tier_NA_Tooltip => ResourceManager.GetString(nameof(Tier_NA_Tooltip), Culture) ?? nameof(Tier_NA_Tooltip);

    public static string Tier_NotHooked => ResourceManager.GetString(nameof(Tier_NotHooked), Culture) ?? nameof(Tier_NotHooked);

    public static string Tier_NotHooked_Tooltip => ResourceManager.GetString(nameof(Tier_NotHooked_Tooltip), Culture) ?? nameof(Tier_NotHooked_Tooltip);

    public static string Trend_Average_Note => ResourceManager.GetString(nameof(Trend_Average_Note), Culture) ?? nameof(Trend_Average_Note);

    public static string Trend_Axis_Date => ResourceManager.GetString(nameof(Trend_Axis_Date), Culture) ?? nameof(Trend_Axis_Date);

    public static string Trend_Change_Cpu => ResourceManager.GetString(nameof(Trend_Change_Cpu), Culture) ?? nameof(Trend_Change_Cpu);

    public static string Trend_Change_Display => ResourceManager.GetString(nameof(Trend_Change_Display), Culture) ?? nameof(Trend_Change_Display);

    public static string Trend_Change_Format => ResourceManager.GetString(nameof(Trend_Change_Format), Culture) ?? nameof(Trend_Change_Format);

    public static string Trend_Change_Gpu => ResourceManager.GetString(nameof(Trend_Change_Gpu), Culture) ?? nameof(Trend_Change_Gpu);

    public static string Trend_Change_GpuDriver => ResourceManager.GetString(nameof(Trend_Change_GpuDriver), Culture) ?? nameof(Trend_Change_GpuDriver);

    public static string Trend_Change_Os => ResourceManager.GetString(nameof(Trend_Change_Os), Culture) ?? nameof(Trend_Change_Os);

    public static string Trend_Empty => ResourceManager.GetString(nameof(Trend_Empty), Culture) ?? nameof(Trend_Empty);

    public static string Trend_Excluded_Format => ResourceManager.GetString(nameof(Trend_Excluded_Format), Culture) ?? nameof(Trend_Excluded_Format);

    public static string Trend_IncludeMidSession => ResourceManager.GetString(nameof(Trend_IncludeMidSession), Culture) ?? nameof(Trend_IncludeMidSession);

    public static string Trend_Metric_Average => ResourceManager.GetString(nameof(Trend_Metric_Average), Culture) ?? nameof(Trend_Metric_Average);

    public static string Trend_Metric_Displayed => ResourceManager.GetString(nameof(Trend_Metric_Displayed), Culture) ?? nameof(Trend_Metric_Displayed);

    public static string Trend_Metric_Label => ResourceManager.GetString(nameof(Trend_Metric_Label), Culture) ?? nameof(Trend_Metric_Label);

    public static string Trend_Metric_MaxGpuTemp => ResourceManager.GetString(nameof(Trend_Metric_MaxGpuTemp), Culture) ?? nameof(Trend_Metric_MaxGpuTemp);

    public static string Trend_Metric_P01Low => ResourceManager.GetString(nameof(Trend_Metric_P01Low), Culture) ?? nameof(Trend_Metric_P01Low);

    public static string Trend_Metric_P1Low => ResourceManager.GetString(nameof(Trend_Metric_P1Low), Culture) ?? nameof(Trend_Metric_P1Low);

    public static string Upscaler_None => ResourceManager.GetString(nameof(Upscaler_None), Culture) ?? nameof(Upscaler_None);

    public static string Upscaler_Unknown => ResourceManager.GetString(nameof(Upscaler_Unknown), Culture) ?? nameof(Upscaler_Unknown);
}
