// <auto-generated>
//     Generated by tools/resx-gen.ps1 from Strings.resx. DO NOT EDIT BY HAND:
//     run the tool, or `./build.ps1 check` will fail the resx-audit gate on the drift.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace FrameLedger.App;

/// <summary>The user-visible strings (docs/09_I18N.md), one property per key, read through the current UI culture.</summary>
[GeneratedCode("tools/resx-gen.ps1", "1")]
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>The culture the properties read with; null means the current UI culture.</summary>
    public static CultureInfo? Culture { get; set; }

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("FrameLedger.App.Strings", typeof(Strings).Assembly);

    /// <summary>Every key, for an audit that walks them.</summary>
    public static IReadOnlyList<string> Keys { get; } =
    [
        nameof(About_Body_Format),
        nameof(About_Title),
        nameof(Agent_Banner_Missing_Body),
        nameof(Agent_Banner_Offline_Body),
        nameof(Agent_Banner_Offline_Title),
        nameof(Agent_Banner_Retry),
        nameof(Agent_State_Connected),
        nameof(Agent_State_Connecting),
        nameof(Agent_State_Missing),
        nameof(Agent_State_Offline),
        nameof(Agent_State_Starting),
        nameof(App_Title),
        nameof(Common_Cancel),
        nameof(Common_No),
        nameof(Common_NotAvailable),
        nameof(Common_Ok),
        nameof(Common_Yes),
        nameof(Compare_Empty),
        nameof(Compare_Header),
        nameof(Crash_Body),
        nameof(Crash_Title),
        nameof(Dashboard_Agent_Elevated),
        nameof(Dashboard_Agent_Header),
        nameof(Dashboard_Agent_Overlay),
        nameof(Dashboard_Agent_Sessions),
        nameof(Dashboard_Agent_State),
        nameof(Dashboard_Agent_Telemetry),
        nameof(Dashboard_Agent_Version),
        nameof(Dashboard_Empty),
        nameof(Dashboard_Header),
        nameof(Games_Empty),
        nameof(Games_Header),
        nameof(Logs_Empty),
        nameof(Logs_Header),
        nameof(Menu_File),
        nameof(Menu_File_AddGame),
        nameof(Menu_File_Exit),
        nameof(Menu_File_Export),
        nameof(Menu_File_ImportLibrary),
        nameof(Menu_Help),
        nameof(Menu_Help_About),
        nameof(Menu_Help_CheckUpdates),
        nameof(Menu_Help_Documentation),
        nameof(Menu_Help_ReportBug),
        nameof(Menu_Tools),
        nameof(Menu_Tools_AgentStatus),
        nameof(Menu_Tools_DbMaintenance),
        nameof(Menu_Tools_OpenDataFolder),
        nameof(Menu_Tools_UpdateRules),
        nameof(Menu_Tools_VulkanLayer),
        nameof(Nav_Compare),
        nameof(Nav_Dashboard),
        nameof(Nav_Games),
        nameof(Nav_Logs),
        nameof(Nav_Settings),
        nameof(NotYet_Body),
        nameof(NotYet_Title),
        nameof(Settings_Appearance_Header),
        nameof(Settings_Header),
        nameof(Settings_Language_Label),
        nameof(Settings_Language_Note),
        nameof(Settings_Theme_Dark),
        nameof(Settings_Theme_Label),
        nameof(Settings_Theme_Light),
        nameof(Settings_Theme_System),
    ];

    public static string About_Body_Format => ResourceManager.GetString(nameof(About_Body_Format), Culture) ?? nameof(About_Body_Format);

    public static string About_Title => ResourceManager.GetString(nameof(About_Title), Culture) ?? nameof(About_Title);

    public static string Agent_Banner_Missing_Body => ResourceManager.GetString(nameof(Agent_Banner_Missing_Body), Culture) ?? nameof(Agent_Banner_Missing_Body);

    public static string Agent_Banner_Offline_Body => ResourceManager.GetString(nameof(Agent_Banner_Offline_Body), Culture) ?? nameof(Agent_Banner_Offline_Body);

    public static string Agent_Banner_Offline_Title => ResourceManager.GetString(nameof(Agent_Banner_Offline_Title), Culture) ?? nameof(Agent_Banner_Offline_Title);

    public static string Agent_Banner_Retry => ResourceManager.GetString(nameof(Agent_Banner_Retry), Culture) ?? nameof(Agent_Banner_Retry);

    public static string Agent_State_Connected => ResourceManager.GetString(nameof(Agent_State_Connected), Culture) ?? nameof(Agent_State_Connected);

    public static string Agent_State_Connecting => ResourceManager.GetString(nameof(Agent_State_Connecting), Culture) ?? nameof(Agent_State_Connecting);

    public static string Agent_State_Missing => ResourceManager.GetString(nameof(Agent_State_Missing), Culture) ?? nameof(Agent_State_Missing);

    public static string Agent_State_Offline => ResourceManager.GetString(nameof(Agent_State_Offline), Culture) ?? nameof(Agent_State_Offline);

    public static string Agent_State_Starting => ResourceManager.GetString(nameof(Agent_State_Starting), Culture) ?? nameof(Agent_State_Starting);

    public static string App_Title => ResourceManager.GetString(nameof(App_Title), Culture) ?? nameof(App_Title);

    public static string Common_Cancel => ResourceManager.GetString(nameof(Common_Cancel), Culture) ?? nameof(Common_Cancel);

    public static string Common_No => ResourceManager.GetString(nameof(Common_No), Culture) ?? nameof(Common_No);

    public static string Common_NotAvailable => ResourceManager.GetString(nameof(Common_NotAvailable), Culture) ?? nameof(Common_NotAvailable);

    public static string Common_Ok => ResourceManager.GetString(nameof(Common_Ok), Culture) ?? nameof(Common_Ok);

    public static string Common_Yes => ResourceManager.GetString(nameof(Common_Yes), Culture) ?? nameof(Common_Yes);

    public static string Compare_Empty => ResourceManager.GetString(nameof(Compare_Empty), Culture) ?? nameof(Compare_Empty);

    public static string Compare_Header => ResourceManager.GetString(nameof(Compare_Header), Culture) ?? nameof(Compare_Header);

    public static string Crash_Body => ResourceManager.GetString(nameof(Crash_Body), Culture) ?? nameof(Crash_Body);

    public static string Crash_Title => ResourceManager.GetString(nameof(Crash_Title), Culture) ?? nameof(Crash_Title);

    public static string Dashboard_Agent_Elevated => ResourceManager.GetString(nameof(Dashboard_Agent_Elevated), Culture) ?? nameof(Dashboard_Agent_Elevated);

    public static string Dashboard_Agent_Header => ResourceManager.GetString(nameof(Dashboard_Agent_Header), Culture) ?? nameof(Dashboard_Agent_Header);

    public static string Dashboard_Agent_Overlay => ResourceManager.GetString(nameof(Dashboard_Agent_Overlay), Culture) ?? nameof(Dashboard_Agent_Overlay);

    public static string Dashboard_Agent_Sessions => ResourceManager.GetString(nameof(Dashboard_Agent_Sessions), Culture) ?? nameof(Dashboard_Agent_Sessions);

    public static string Dashboard_Agent_State => ResourceManager.GetString(nameof(Dashboard_Agent_State), Culture) ?? nameof(Dashboard_Agent_State);

    public static string Dashboard_Agent_Telemetry => ResourceManager.GetString(nameof(Dashboard_Agent_Telemetry), Culture) ?? nameof(Dashboard_Agent_Telemetry);

    public static string Dashboard_Agent_Version => ResourceManager.GetString(nameof(Dashboard_Agent_Version), Culture) ?? nameof(Dashboard_Agent_Version);

    public static string Dashboard_Empty => ResourceManager.GetString(nameof(Dashboard_Empty), Culture) ?? nameof(Dashboard_Empty);

    public static string Dashboard_Header => ResourceManager.GetString(nameof(Dashboard_Header), Culture) ?? nameof(Dashboard_Header);

    public static string Games_Empty => ResourceManager.GetString(nameof(Games_Empty), Culture) ?? nameof(Games_Empty);

    public static string Games_Header => ResourceManager.GetString(nameof(Games_Header), Culture) ?? nameof(Games_Header);

    public static string Logs_Empty => ResourceManager.GetString(nameof(Logs_Empty), Culture) ?? nameof(Logs_Empty);

    public static string Logs_Header => ResourceManager.GetString(nameof(Logs_Header), Culture) ?? nameof(Logs_Header);

    public static string Menu_File => ResourceManager.GetString(nameof(Menu_File), Culture) ?? nameof(Menu_File);

    public static string Menu_File_AddGame => ResourceManager.GetString(nameof(Menu_File_AddGame), Culture) ?? nameof(Menu_File_AddGame);

    public static string Menu_File_Exit => ResourceManager.GetString(nameof(Menu_File_Exit), Culture) ?? nameof(Menu_File_Exit);

    public static string Menu_File_Export => ResourceManager.GetString(nameof(Menu_File_Export), Culture) ?? nameof(Menu_File_Export);

    public static string Menu_File_ImportLibrary => ResourceManager.GetString(nameof(Menu_File_ImportLibrary), Culture) ?? nameof(Menu_File_ImportLibrary);

    public static string Menu_Help => ResourceManager.GetString(nameof(Menu_Help), Culture) ?? nameof(Menu_Help);

    public static string Menu_Help_About => ResourceManager.GetString(nameof(Menu_Help_About), Culture) ?? nameof(Menu_Help_About);

    public static string Menu_Help_CheckUpdates => ResourceManager.GetString(nameof(Menu_Help_CheckUpdates), Culture) ?? nameof(Menu_Help_CheckUpdates);

    public static string Menu_Help_Documentation => ResourceManager.GetString(nameof(Menu_Help_Documentation), Culture) ?? nameof(Menu_Help_Documentation);

    public static string Menu_Help_ReportBug => ResourceManager.GetString(nameof(Menu_Help_ReportBug), Culture) ?? nameof(Menu_Help_ReportBug);

    public static string Menu_Tools => ResourceManager.GetString(nameof(Menu_Tools), Culture) ?? nameof(Menu_Tools);

    public static string Menu_Tools_AgentStatus => ResourceManager.GetString(nameof(Menu_Tools_AgentStatus), Culture) ?? nameof(Menu_Tools_AgentStatus);

    public static string Menu_Tools_DbMaintenance => ResourceManager.GetString(nameof(Menu_Tools_DbMaintenance), Culture) ?? nameof(Menu_Tools_DbMaintenance);

    public static string Menu_Tools_OpenDataFolder => ResourceManager.GetString(nameof(Menu_Tools_OpenDataFolder), Culture) ?? nameof(Menu_Tools_OpenDataFolder);

    public static string Menu_Tools_UpdateRules => ResourceManager.GetString(nameof(Menu_Tools_UpdateRules), Culture) ?? nameof(Menu_Tools_UpdateRules);

    public static string Menu_Tools_VulkanLayer => ResourceManager.GetString(nameof(Menu_Tools_VulkanLayer), Culture) ?? nameof(Menu_Tools_VulkanLayer);

    public static string Nav_Compare => ResourceManager.GetString(nameof(Nav_Compare), Culture) ?? nameof(Nav_Compare);

    public static string Nav_Dashboard => ResourceManager.GetString(nameof(Nav_Dashboard), Culture) ?? nameof(Nav_Dashboard);

    public static string Nav_Games => ResourceManager.GetString(nameof(Nav_Games), Culture) ?? nameof(Nav_Games);

    public static string Nav_Logs => ResourceManager.GetString(nameof(Nav_Logs), Culture) ?? nameof(Nav_Logs);

    public static string Nav_Settings => ResourceManager.GetString(nameof(Nav_Settings), Culture) ?? nameof(Nav_Settings);

    public static string NotYet_Body => ResourceManager.GetString(nameof(NotYet_Body), Culture) ?? nameof(NotYet_Body);

    public static string NotYet_Title => ResourceManager.GetString(nameof(NotYet_Title), Culture) ?? nameof(NotYet_Title);

    public static string Settings_Appearance_Header => ResourceManager.GetString(nameof(Settings_Appearance_Header), Culture) ?? nameof(Settings_Appearance_Header);

    public static string Settings_Header => ResourceManager.GetString(nameof(Settings_Header), Culture) ?? nameof(Settings_Header);

    public static string Settings_Language_Label => ResourceManager.GetString(nameof(Settings_Language_Label), Culture) ?? nameof(Settings_Language_Label);

    public static string Settings_Language_Note => ResourceManager.GetString(nameof(Settings_Language_Note), Culture) ?? nameof(Settings_Language_Note);

    public static string Settings_Theme_Dark => ResourceManager.GetString(nameof(Settings_Theme_Dark), Culture) ?? nameof(Settings_Theme_Dark);

    public static string Settings_Theme_Label => ResourceManager.GetString(nameof(Settings_Theme_Label), Culture) ?? nameof(Settings_Theme_Label);

    public static string Settings_Theme_Light => ResourceManager.GetString(nameof(Settings_Theme_Light), Culture) ?? nameof(Settings_Theme_Light);

    public static string Settings_Theme_System => ResourceManager.GetString(nameof(Settings_Theme_System), Culture) ?? nameof(Settings_Theme_System);
}
