#Requires -Version 7.0
<#
.SYNOPSIS
    Generates the strongly-typed accessor (Strings.Designer.cs) for a neutral .resx, or checks that the
    committed one is current.

.DESCRIPTION
    docs/09_I18N.md: user-visible text is reached "through a generated strongly-typed class; no string
    literals in XAML/C#". Visual Studio's ResXFileCodeGenerator is a design-time tool and `dotnet build`
    never runs it, and MSBuild on .NET Core cannot generate the class itself (GenerateResource's
    StronglyTypedLanguage is unsupported there). So the accessor is GENERATED BY THIS SCRIPT AND COMMITTED,
    and tools/resx-audit.ps1 fails the build when the committed file is not what this script would write —
    which is what makes "generated" true rather than a word in a comment.

    One property per key, sorted, `ResourceManager.GetString(key, Culture)`. The resource base name is
    `<Namespace>.<ClassName>`, which is what the SDK embeds a `<ClassName>.resx` sitting in the project
    directory as. The namespace comes from the csproj in the same directory (<RootNamespace>, else the
    project file name); a directory with no csproj — the audit's self-test fixtures — uses the directory name.

.PARAMETER Resx
    The NEUTRAL resx (Strings.resx, never Strings.vi.resx).

.PARAMETER Check
    Do not write; exit 1 when the committed Designer differs from what would be written (or is absent).
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$Resx,

    [string]$Namespace,

    [string]$ClassName,

    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$resxPath = (Resolve-Path $Resx).Path
$dir = Split-Path $resxPath -Parent
if (-not $ClassName) { $ClassName = [IO.Path]::GetFileNameWithoutExtension($resxPath) }
if ($ClassName -match '\.') { throw "resx-gen: '$Resx' looks like a culture-specific file; pass the neutral one" }

if (-not $Namespace) {
    $csproj = Get-ChildItem $dir -Filter '*.csproj' -File | Select-Object -First 1
    if ($csproj) {
        [xml]$proj = Get-Content -Raw $csproj.FullName
        $rootNs = $proj.SelectSingleNode('//RootNamespace')
        $Namespace = if ($rootNs -and $rootNs.InnerText.Trim()) { $rootNs.InnerText.Trim() } else { [IO.Path]::GetFileNameWithoutExtension($csproj.Name) }
    }
    else {
        $Namespace = Split-Path $dir -Leaf
    }
}

[xml]$doc = Get-Content -Raw $resxPath
$keys = @($doc.root.data | ForEach-Object { $_.name } | Sort-Object -Culture 'en-US' -CaseSensitive)
foreach ($k in $keys) {
    if ($k -notmatch '^[A-Za-z][A-Za-z0-9_]*$') { throw "resx-gen: key '$k' is not a C# identifier" }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('// <auto-generated>')
$lines.Add("//     Generated by tools/resx-gen.ps1 from $([IO.Path]::GetFileName($resxPath)). DO NOT EDIT BY HAND:")
$lines.Add('//     run the tool, or `./build.ps1 check` will fail the resx-audit gate on the drift.')
$lines.Add('// </auto-generated>')
$lines.Add('')
$lines.Add('#nullable enable')
$lines.Add('')
$lines.Add('using System.CodeDom.Compiler;')
$lines.Add('using System.Globalization;')
$lines.Add('using System.Resources;')
$lines.Add('')
$lines.Add("namespace $Namespace;")
$lines.Add('')
$lines.Add('/// <summary>The user-visible strings (docs/09_I18N.md), one property per key, read through the current UI culture.</summary>')
$lines.Add('[GeneratedCode("tools/resx-gen.ps1", "1")]')
$lines.Add("public static class $ClassName")
$lines.Add('{')
$lines.Add('    private static ResourceManager? _resourceManager;')
$lines.Add('')
$lines.Add('    /// <summary>The culture the properties read with; null means the current UI culture.</summary>')
$lines.Add('    public static CultureInfo? Culture { get; set; }')
$lines.Add('')
$lines.Add('    public static ResourceManager ResourceManager =>')
$lines.Add("        _resourceManager ??= new ResourceManager(""$Namespace.$ClassName"", typeof($ClassName).Assembly);")
$lines.Add('')
$lines.Add('    /// <summary>Every key, for an audit that walks them.</summary>')
$lines.Add('    public static IReadOnlyList<string> Keys { get; } =')
$lines.Add('    [')
foreach ($k in $keys) { $lines.Add("        nameof($k),") }
$lines.Add('    ];')
foreach ($k in $keys) {
    $lines.Add('')
    $lines.Add("    public static string $k => ResourceManager.GetString(nameof($k), Culture) ?? nameof($k);")
}
$lines.Add('}')
$text = ($lines -join "`r`n") + "`r`n"

$outPath = Join-Path $dir "$ClassName.Designer.cs"
if ($Check) {
    if (-not (Test-Path $outPath)) {
        Write-Host "resx-gen: $outPath is missing — run tools/resx-gen.ps1 -Resx $Resx" -ForegroundColor Red
        exit 1
    }

    $existing = [IO.File]::ReadAllText($outPath) -replace "`r`n", "`n"
    if ($existing -ne ($text -replace "`r`n", "`n")) {
        Write-Host "resx-gen: $outPath is not what $([IO.Path]::GetFileName($resxPath)) generates — run tools/resx-gen.ps1 -Resx $Resx" -ForegroundColor Red
        exit 1
    }

    Write-Host "resx-gen: $outPath is current ($($keys.Count) key(s))" -ForegroundColor DarkGray
    exit 0
}

[IO.File]::WriteAllText($outPath, $text, [Text.UTF8Encoding]::new($false))
Write-Host "resx-gen: wrote $outPath ($($keys.Count) key(s), namespace $Namespace)" -ForegroundColor Green
exit 0
